// Code generated by ent, DO NOT EDIT.

package workspace

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldDescription, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldStatus, v))
}

// PermAccountManage applies equality check predicate on the "perm_account_manage" field. It's identical to PermAccountManageEQ.
func PermAccountManage(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldPermAccountManage, v))
}

// PermGroupOps applies equality check predicate on the "perm_group_ops" field. It's identical to PermGroupOpsEQ.
func PermGroupOps(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldPermGroupOps, v))
}

// PermGroupBilling applies equality check predicate on the "perm_group_billing" field. It's identical to PermGroupBillingEQ.
func PermGroupBilling(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldPermGroupBilling, v))
}

// PermProxyManage applies equality check predicate on the "perm_proxy_manage" field. It's identical to PermProxyManageEQ.
func PermProxyManage(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldPermProxyManage, v))
}

// PermMonitorView applies equality check predicate on the "perm_monitor_view" field. It's identical to PermMonitorViewEQ.
func PermMonitorView(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldPermMonitorView, v))
}

// SettlementRateMin applies equality check predicate on the "settlement_rate_min" field. It's identical to SettlementRateMinEQ.
func SettlementRateMin(v float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldSettlementRateMin, v))
}

// SettlementRateMax applies equality check predicate on the "settlement_rate_max" field. It's identical to SettlementRateMaxEQ.
func SettlementRateMax(v float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldSettlementRateMax, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Workspace {
	return predicate.Workspace(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Workspace {
	return predicate.Workspace(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldStatus, v))
}

// PermAccountManageEQ applies the EQ predicate on the "perm_account_manage" field.
func PermAccountManageEQ(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldPermAccountManage, v))
}

// PermAccountManageNEQ applies the NEQ predicate on the "perm_account_manage" field.
func PermAccountManageNEQ(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldPermAccountManage, v))
}

// PermGroupOpsEQ applies the EQ predicate on the "perm_group_ops" field.
func PermGroupOpsEQ(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldPermGroupOps, v))
}

// PermGroupOpsNEQ applies the NEQ predicate on the "perm_group_ops" field.
func PermGroupOpsNEQ(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldPermGroupOps, v))
}

// PermGroupBillingEQ applies the EQ predicate on the "perm_group_billing" field.
func PermGroupBillingEQ(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldPermGroupBilling, v))
}

// PermGroupBillingNEQ applies the NEQ predicate on the "perm_group_billing" field.
func PermGroupBillingNEQ(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldPermGroupBilling, v))
}

// PermProxyManageEQ applies the EQ predicate on the "perm_proxy_manage" field.
func PermProxyManageEQ(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldPermProxyManage, v))
}

// PermProxyManageNEQ applies the NEQ predicate on the "perm_proxy_manage" field.
func PermProxyManageNEQ(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldPermProxyManage, v))
}

// PermMonitorViewEQ applies the EQ predicate on the "perm_monitor_view" field.
func PermMonitorViewEQ(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldPermMonitorView, v))
}

// PermMonitorViewNEQ applies the NEQ predicate on the "perm_monitor_view" field.
func PermMonitorViewNEQ(v bool) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldPermMonitorView, v))
}

// SettlementRateMinEQ applies the EQ predicate on the "settlement_rate_min" field.
func SettlementRateMinEQ(v float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldSettlementRateMin, v))
}

// SettlementRateMinNEQ applies the NEQ predicate on the "settlement_rate_min" field.
func SettlementRateMinNEQ(v float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldSettlementRateMin, v))
}

// SettlementRateMinIn applies the In predicate on the "settlement_rate_min" field.
func SettlementRateMinIn(vs ...float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldSettlementRateMin, vs...))
}

// SettlementRateMinNotIn applies the NotIn predicate on the "settlement_rate_min" field.
func SettlementRateMinNotIn(vs ...float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldSettlementRateMin, vs...))
}

// SettlementRateMinGT applies the GT predicate on the "settlement_rate_min" field.
func SettlementRateMinGT(v float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldSettlementRateMin, v))
}

// SettlementRateMinGTE applies the GTE predicate on the "settlement_rate_min" field.
func SettlementRateMinGTE(v float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldSettlementRateMin, v))
}

// SettlementRateMinLT applies the LT predicate on the "settlement_rate_min" field.
func SettlementRateMinLT(v float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldSettlementRateMin, v))
}

// SettlementRateMinLTE applies the LTE predicate on the "settlement_rate_min" field.
func SettlementRateMinLTE(v float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldSettlementRateMin, v))
}

// SettlementRateMinIsNil applies the IsNil predicate on the "settlement_rate_min" field.
func SettlementRateMinIsNil() predicate.Workspace {
	return predicate.Workspace(sql.FieldIsNull(FieldSettlementRateMin))
}

// SettlementRateMinNotNil applies the NotNil predicate on the "settlement_rate_min" field.
func SettlementRateMinNotNil() predicate.Workspace {
	return predicate.Workspace(sql.FieldNotNull(FieldSettlementRateMin))
}

// SettlementRateMaxEQ applies the EQ predicate on the "settlement_rate_max" field.
func SettlementRateMaxEQ(v float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldSettlementRateMax, v))
}

// SettlementRateMaxNEQ applies the NEQ predicate on the "settlement_rate_max" field.
func SettlementRateMaxNEQ(v float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldSettlementRateMax, v))
}

// SettlementRateMaxIn applies the In predicate on the "settlement_rate_max" field.
func SettlementRateMaxIn(vs ...float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldSettlementRateMax, vs...))
}

// SettlementRateMaxNotIn applies the NotIn predicate on the "settlement_rate_max" field.
func SettlementRateMaxNotIn(vs ...float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldSettlementRateMax, vs...))
}

// SettlementRateMaxGT applies the GT predicate on the "settlement_rate_max" field.
func SettlementRateMaxGT(v float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldSettlementRateMax, v))
}

// SettlementRateMaxGTE applies the GTE predicate on the "settlement_rate_max" field.
func SettlementRateMaxGTE(v float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldSettlementRateMax, v))
}

// SettlementRateMaxLT applies the LT predicate on the "settlement_rate_max" field.
func SettlementRateMaxLT(v float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldSettlementRateMax, v))
}

// SettlementRateMaxLTE applies the LTE predicate on the "settlement_rate_max" field.
func SettlementRateMaxLTE(v float64) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldSettlementRateMax, v))
}

// SettlementRateMaxIsNil applies the IsNil predicate on the "settlement_rate_max" field.
func SettlementRateMaxIsNil() predicate.Workspace {
	return predicate.Workspace(sql.FieldIsNull(FieldSettlementRateMax))
}

// SettlementRateMaxNotNil applies the NotNil predicate on the "settlement_rate_max" field.
func SettlementRateMaxNotNil() predicate.Workspace {
	return predicate.Workspace(sql.FieldNotNull(FieldSettlementRateMax))
}

// HasMembers applies the HasEdge predicate on the "members" edge.
func HasMembers() predicate.Workspace {
	return predicate.Workspace(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMembersWith applies the HasEdge predicate on the "members" edge with a given conditions (other predicates).
func HasMembersWith(preds ...predicate.WorkspaceMember) predicate.Workspace {
	return predicate.Workspace(func(s *sql.Selector) {
		step := newMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Workspace) predicate.Workspace {
	return predicate.Workspace(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Workspace) predicate.Workspace {
	return predicate.Workspace(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Workspace) predicate.Workspace {
	return predicate.Workspace(sql.NotPredicates(p))
}
