// Code generated by ent, DO NOT EDIT.

package workspace

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the workspace type in the database.
	Label = "workspace"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPermAccountManage holds the string denoting the perm_account_manage field in the database.
	FieldPermAccountManage = "perm_account_manage"
	// FieldPermGroupOps holds the string denoting the perm_group_ops field in the database.
	FieldPermGroupOps = "perm_group_ops"
	// FieldPermGroupBilling holds the string denoting the perm_group_billing field in the database.
	FieldPermGroupBilling = "perm_group_billing"
	// FieldPermProxyManage holds the string denoting the perm_proxy_manage field in the database.
	FieldPermProxyManage = "perm_proxy_manage"
	// FieldPermMonitorView holds the string denoting the perm_monitor_view field in the database.
	FieldPermMonitorView = "perm_monitor_view"
	// FieldSettlementRateMin holds the string denoting the settlement_rate_min field in the database.
	FieldSettlementRateMin = "settlement_rate_min"
	// FieldSettlementRateMax holds the string denoting the settlement_rate_max field in the database.
	FieldSettlementRateMax = "settlement_rate_max"
	// EdgeMembers holds the string denoting the members edge name in mutations.
	EdgeMembers = "members"
	// Table holds the table name of the workspace in the database.
	Table = "workspaces"
	// MembersTable is the table that holds the members relation/edge.
	MembersTable = "workspace_members"
	// MembersInverseTable is the table name for the WorkspaceMember entity.
	// It exists in this package in order to avoid circular dependency with the "workspacemember" package.
	MembersInverseTable = "workspace_members"
	// MembersColumn is the table column denoting the members relation/edge.
	MembersColumn = "workspace_id"
)

// Columns holds all SQL columns for workspace fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldDescription,
	FieldStatus,
	FieldPermAccountManage,
	FieldPermGroupOps,
	FieldPermGroupBilling,
	FieldPermProxyManage,
	FieldPermMonitorView,
	FieldSettlementRateMin,
	FieldSettlementRateMax,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultPermAccountManage holds the default value on creation for the "perm_account_manage" field.
	DefaultPermAccountManage bool
	// DefaultPermGroupOps holds the default value on creation for the "perm_group_ops" field.
	DefaultPermGroupOps bool
	// DefaultPermGroupBilling holds the default value on creation for the "perm_group_billing" field.
	DefaultPermGroupBilling bool
	// DefaultPermProxyManage holds the default value on creation for the "perm_proxy_manage" field.
	DefaultPermProxyManage bool
	// DefaultPermMonitorView holds the default value on creation for the "perm_monitor_view" field.
	DefaultPermMonitorView bool
)

// OrderOption defines the ordering options for the Workspace queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPermAccountManage orders the results by the perm_account_manage field.
func ByPermAccountManage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPermAccountManage, opts...).ToFunc()
}

// ByPermGroupOps orders the results by the perm_group_ops field.
func ByPermGroupOps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPermGroupOps, opts...).ToFunc()
}

// ByPermGroupBilling orders the results by the perm_group_billing field.
func ByPermGroupBilling(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPermGroupBilling, opts...).ToFunc()
}

// ByPermProxyManage orders the results by the perm_proxy_manage field.
func ByPermProxyManage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPermProxyManage, opts...).ToFunc()
}

// ByPermMonitorView orders the results by the perm_monitor_view field.
func ByPermMonitorView(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPermMonitorView, opts...).ToFunc()
}

// BySettlementRateMin orders the results by the settlement_rate_min field.
func BySettlementRateMin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementRateMin, opts...).ToFunc()
}

// BySettlementRateMax orders the results by the settlement_rate_max field.
func BySettlementRateMax(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementRateMax, opts...).ToFunc()
}

// ByMembersCount orders the results by members count.
func ByMembersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMembersStep(), opts...)
	}
}

// ByMembers orders the results by members terms.
func ByMembers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMembersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMembersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MembersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
	)
}
