// Code generated by ent, DO NOT EDIT.

package workspacegroupgrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldLTE(FieldID, id))
}

// WorkspaceID applies equality check predicate on the "workspace_id" field. It's identical to WorkspaceIDEQ.
func WorkspaceID(v int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldEQ(FieldWorkspaceID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldEQ(FieldGroupID, v))
}

// BasePriority applies equality check predicate on the "base_priority" field. It's identical to BasePriorityEQ.
func BasePriority(v int) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldEQ(FieldBasePriority, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// WorkspaceIDEQ applies the EQ predicate on the "workspace_id" field.
func WorkspaceIDEQ(v int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldEQ(FieldWorkspaceID, v))
}

// WorkspaceIDNEQ applies the NEQ predicate on the "workspace_id" field.
func WorkspaceIDNEQ(v int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldNEQ(FieldWorkspaceID, v))
}

// WorkspaceIDIn applies the In predicate on the "workspace_id" field.
func WorkspaceIDIn(vs ...int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDNotIn applies the NotIn predicate on the "workspace_id" field.
func WorkspaceIDNotIn(vs ...int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldNotIn(FieldWorkspaceID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldNotIn(FieldGroupID, vs...))
}

// BasePriorityEQ applies the EQ predicate on the "base_priority" field.
func BasePriorityEQ(v int) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldEQ(FieldBasePriority, v))
}

// BasePriorityNEQ applies the NEQ predicate on the "base_priority" field.
func BasePriorityNEQ(v int) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldNEQ(FieldBasePriority, v))
}

// BasePriorityIn applies the In predicate on the "base_priority" field.
func BasePriorityIn(vs ...int) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldIn(FieldBasePriority, vs...))
}

// BasePriorityNotIn applies the NotIn predicate on the "base_priority" field.
func BasePriorityNotIn(vs ...int) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldNotIn(FieldBasePriority, vs...))
}

// BasePriorityGT applies the GT predicate on the "base_priority" field.
func BasePriorityGT(v int) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldGT(FieldBasePriority, v))
}

// BasePriorityGTE applies the GTE predicate on the "base_priority" field.
func BasePriorityGTE(v int) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldGTE(FieldBasePriority, v))
}

// BasePriorityLT applies the LT predicate on the "base_priority" field.
func BasePriorityLT(v int) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldLT(FieldBasePriority, v))
}

// BasePriorityLTE applies the LTE predicate on the "base_priority" field.
func BasePriorityLTE(v int) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldLTE(FieldBasePriority, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasWorkspace applies the HasEdge predicate on the "workspace" edge.
func HasWorkspace() predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, WorkspaceTable, WorkspaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkspaceWith applies the HasEdge predicate on the "workspace" edge with a given conditions (other predicates).
func HasWorkspaceWith(preds ...predicate.Workspace) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(func(s *sql.Selector) {
		step := newWorkspaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkspaceGroupGrant) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkspaceGroupGrant) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkspaceGroupGrant) predicate.WorkspaceGroupGrant {
	return predicate.WorkspaceGroupGrant(sql.NotPredicates(p))
}
