// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adminuseradjustment"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// AdminUserAdjustmentUpdate is the builder for updating AdminUserAdjustment entities.
type AdminUserAdjustmentUpdate struct {
	config
	hooks    []Hook
	mutation *AdminUserAdjustmentMutation
}

// Where appends a list predicates to the AdminUserAdjustmentUpdate builder.
func (_u *AdminUserAdjustmentUpdate) Where(ps ...predicate.AdminUserAdjustment) *AdminUserAdjustmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetActionID sets the "action_id" field.
func (_u *AdminUserAdjustmentUpdate) SetActionID(v uuid.UUID) *AdminUserAdjustmentUpdate {
	_u.mutation.SetActionID(v)
	return _u
}

// SetNillableActionID sets the "action_id" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableActionID(v *uuid.UUID) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetActionID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *AdminUserAdjustmentUpdate) SetKind(v string) *AdminUserAdjustmentUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableKind(v *string) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *AdminUserAdjustmentUpdate) SetOperation(v string) *AdminUserAdjustmentUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableOperation(v *string) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetRequestedValue sets the "requested_value" field.
func (_u *AdminUserAdjustmentUpdate) SetRequestedValue(v string) *AdminUserAdjustmentUpdate {
	_u.mutation.SetRequestedValue(v)
	return _u
}

// SetNillableRequestedValue sets the "requested_value" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableRequestedValue(v *string) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetRequestedValue(*v)
	}
	return _u
}

// ClearRequestedValue clears the value of the "requested_value" field.
func (_u *AdminUserAdjustmentUpdate) ClearRequestedValue() *AdminUserAdjustmentUpdate {
	_u.mutation.ClearRequestedValue()
	return _u
}

// SetDelta sets the "delta" field.
func (_u *AdminUserAdjustmentUpdate) SetDelta(v string) *AdminUserAdjustmentUpdate {
	_u.mutation.SetDelta(v)
	return _u
}

// SetNillableDelta sets the "delta" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableDelta(v *string) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetDelta(*v)
	}
	return _u
}

// SetBeforeValue sets the "before_value" field.
func (_u *AdminUserAdjustmentUpdate) SetBeforeValue(v string) *AdminUserAdjustmentUpdate {
	_u.mutation.SetBeforeValue(v)
	return _u
}

// SetNillableBeforeValue sets the "before_value" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableBeforeValue(v *string) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetBeforeValue(*v)
	}
	return _u
}

// ClearBeforeValue clears the value of the "before_value" field.
func (_u *AdminUserAdjustmentUpdate) ClearBeforeValue() *AdminUserAdjustmentUpdate {
	_u.mutation.ClearBeforeValue()
	return _u
}

// SetAfterValue sets the "after_value" field.
func (_u *AdminUserAdjustmentUpdate) SetAfterValue(v string) *AdminUserAdjustmentUpdate {
	_u.mutation.SetAfterValue(v)
	return _u
}

// SetNillableAfterValue sets the "after_value" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableAfterValue(v *string) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetAfterValue(*v)
	}
	return _u
}

// ClearAfterValue clears the value of the "after_value" field.
func (_u *AdminUserAdjustmentUpdate) ClearAfterValue() *AdminUserAdjustmentUpdate {
	_u.mutation.ClearAfterValue()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AdminUserAdjustmentUpdate) SetUserID(v int64) *AdminUserAdjustmentUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableUserID(v *int64) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AdminUserAdjustmentUpdate) AddUserID(v int64) *AdminUserAdjustmentUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AdminUserAdjustmentUpdate) ClearUserID() *AdminUserAdjustmentUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *AdminUserAdjustmentUpdate) SetUserEmail(v string) *AdminUserAdjustmentUpdate {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableUserEmail(v *string) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// ClearUserEmail clears the value of the "user_email" field.
func (_u *AdminUserAdjustmentUpdate) ClearUserEmail() *AdminUserAdjustmentUpdate {
	_u.mutation.ClearUserEmail()
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *AdminUserAdjustmentUpdate) SetUserName(v string) *AdminUserAdjustmentUpdate {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableUserName(v *string) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// ClearUserName clears the value of the "user_name" field.
func (_u *AdminUserAdjustmentUpdate) ClearUserName() *AdminUserAdjustmentUpdate {
	_u.mutation.ClearUserName()
	return _u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *AdminUserAdjustmentUpdate) SetOperatorUserID(v int64) *AdminUserAdjustmentUpdate {
	_u.mutation.ResetOperatorUserID()
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableOperatorUserID(v *int64) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// AddOperatorUserID adds value to the "operator_user_id" field.
func (_u *AdminUserAdjustmentUpdate) AddOperatorUserID(v int64) *AdminUserAdjustmentUpdate {
	_u.mutation.AddOperatorUserID(v)
	return _u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (_u *AdminUserAdjustmentUpdate) ClearOperatorUserID() *AdminUserAdjustmentUpdate {
	_u.mutation.ClearOperatorUserID()
	return _u
}

// SetOperatorEmail sets the "operator_email" field.
func (_u *AdminUserAdjustmentUpdate) SetOperatorEmail(v string) *AdminUserAdjustmentUpdate {
	_u.mutation.SetOperatorEmail(v)
	return _u
}

// SetNillableOperatorEmail sets the "operator_email" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableOperatorEmail(v *string) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetOperatorEmail(*v)
	}
	return _u
}

// ClearOperatorEmail clears the value of the "operator_email" field.
func (_u *AdminUserAdjustmentUpdate) ClearOperatorEmail() *AdminUserAdjustmentUpdate {
	_u.mutation.ClearOperatorEmail()
	return _u
}

// SetOperatorName sets the "operator_name" field.
func (_u *AdminUserAdjustmentUpdate) SetOperatorName(v string) *AdminUserAdjustmentUpdate {
	_u.mutation.SetOperatorName(v)
	return _u
}

// SetNillableOperatorName sets the "operator_name" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableOperatorName(v *string) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetOperatorName(*v)
	}
	return _u
}

// ClearOperatorName clears the value of the "operator_name" field.
func (_u *AdminUserAdjustmentUpdate) ClearOperatorName() *AdminUserAdjustmentUpdate {
	_u.mutation.ClearOperatorName()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *AdminUserAdjustmentUpdate) SetNotes(v string) *AdminUserAdjustmentUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableNotes(v *string) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *AdminUserAdjustmentUpdate) ClearNotes() *AdminUserAdjustmentUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *AdminUserAdjustmentUpdate) SetClientIP(v string) *AdminUserAdjustmentUpdate {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableClientIP(v *string) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// ClearClientIP clears the value of the "client_ip" field.
func (_u *AdminUserAdjustmentUpdate) ClearClientIP() *AdminUserAdjustmentUpdate {
	_u.mutation.ClearClientIP()
	return _u
}

// SetAuthMethod sets the "auth_method" field.
func (_u *AdminUserAdjustmentUpdate) SetAuthMethod(v string) *AdminUserAdjustmentUpdate {
	_u.mutation.SetAuthMethod(v)
	return _u
}

// SetNillableAuthMethod sets the "auth_method" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableAuthMethod(v *string) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetAuthMethod(*v)
	}
	return _u
}

// ClearAuthMethod clears the value of the "auth_method" field.
func (_u *AdminUserAdjustmentUpdate) ClearAuthMethod() *AdminUserAdjustmentUpdate {
	_u.mutation.ClearAuthMethod()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AdminUserAdjustmentUpdate) SetRequestID(v string) *AdminUserAdjustmentUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableRequestID(v *string) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *AdminUserAdjustmentUpdate) ClearRequestID() *AdminUserAdjustmentUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetSource sets the "source" field.
func (_u *AdminUserAdjustmentUpdate) SetSource(v string) *AdminUserAdjustmentUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableSource(v *string) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetLegacyRedeemCodeID sets the "legacy_redeem_code_id" field.
func (_u *AdminUserAdjustmentUpdate) SetLegacyRedeemCodeID(v int64) *AdminUserAdjustmentUpdate {
	_u.mutation.ResetLegacyRedeemCodeID()
	_u.mutation.SetLegacyRedeemCodeID(v)
	return _u
}

// SetNillableLegacyRedeemCodeID sets the "legacy_redeem_code_id" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdate) SetNillableLegacyRedeemCodeID(v *int64) *AdminUserAdjustmentUpdate {
	if v != nil {
		_u.SetLegacyRedeemCodeID(*v)
	}
	return _u
}

// AddLegacyRedeemCodeID adds value to the "legacy_redeem_code_id" field.
func (_u *AdminUserAdjustmentUpdate) AddLegacyRedeemCodeID(v int64) *AdminUserAdjustmentUpdate {
	_u.mutation.AddLegacyRedeemCodeID(v)
	return _u
}

// ClearLegacyRedeemCodeID clears the value of the "legacy_redeem_code_id" field.
func (_u *AdminUserAdjustmentUpdate) ClearLegacyRedeemCodeID() *AdminUserAdjustmentUpdate {
	_u.mutation.ClearLegacyRedeemCodeID()
	return _u
}

// Mutation returns the AdminUserAdjustmentMutation object of the builder.
func (_u *AdminUserAdjustmentUpdate) Mutation() *AdminUserAdjustmentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminUserAdjustmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminUserAdjustmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminUserAdjustmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminUserAdjustmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminUserAdjustmentUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := adminuseradjustment.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operation(); ok {
		if err := adminuseradjustment.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := adminuseradjustment.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.user_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserName(); ok {
		if err := adminuseradjustment.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.user_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperatorEmail(); ok {
		if err := adminuseradjustment.OperatorEmailValidator(v); err != nil {
			return &ValidationError{Name: "operator_email", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.operator_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperatorName(); ok {
		if err := adminuseradjustment.OperatorNameValidator(v); err != nil {
			return &ValidationError{Name: "operator_name", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.operator_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientIP(); ok {
		if err := adminuseradjustment.ClientIPValidator(v); err != nil {
			return &ValidationError{Name: "client_ip", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.client_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMethod(); ok {
		if err := adminuseradjustment.AuthMethodValidator(v); err != nil {
			return &ValidationError{Name: "auth_method", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.auth_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := adminuseradjustment.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := adminuseradjustment.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.source": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminUserAdjustmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminuseradjustment.Table, adminuseradjustment.Columns, sqlgraph.NewFieldSpec(adminuseradjustment.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActionID(); ok {
		_spec.SetField(adminuseradjustment.FieldActionID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(adminuseradjustment.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(adminuseradjustment.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedValue(); ok {
		_spec.SetField(adminuseradjustment.FieldRequestedValue, field.TypeString, value)
	}
	if _u.mutation.RequestedValueCleared() {
		_spec.ClearField(adminuseradjustment.FieldRequestedValue, field.TypeString)
	}
	if value, ok := _u.mutation.Delta(); ok {
		_spec.SetField(adminuseradjustment.FieldDelta, field.TypeString, value)
	}
	if value, ok := _u.mutation.BeforeValue(); ok {
		_spec.SetField(adminuseradjustment.FieldBeforeValue, field.TypeString, value)
	}
	if _u.mutation.BeforeValueCleared() {
		_spec.ClearField(adminuseradjustment.FieldBeforeValue, field.TypeString)
	}
	if value, ok := _u.mutation.AfterValue(); ok {
		_spec.SetField(adminuseradjustment.FieldAfterValue, field.TypeString, value)
	}
	if _u.mutation.AfterValueCleared() {
		_spec.ClearField(adminuseradjustment.FieldAfterValue, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(adminuseradjustment.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(adminuseradjustment.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(adminuseradjustment.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(adminuseradjustment.FieldUserEmail, field.TypeString, value)
	}
	if _u.mutation.UserEmailCleared() {
		_spec.ClearField(adminuseradjustment.FieldUserEmail, field.TypeString)
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(adminuseradjustment.FieldUserName, field.TypeString, value)
	}
	if _u.mutation.UserNameCleared() {
		_spec.ClearField(adminuseradjustment.FieldUserName, field.TypeString)
	}
	if value, ok := _u.mutation.OperatorUserID(); ok {
		_spec.SetField(adminuseradjustment.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorUserID(); ok {
		_spec.AddField(adminuseradjustment.FieldOperatorUserID, field.TypeInt64, value)
	}
	if _u.mutation.OperatorUserIDCleared() {
		_spec.ClearField(adminuseradjustment.FieldOperatorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.OperatorEmail(); ok {
		_spec.SetField(adminuseradjustment.FieldOperatorEmail, field.TypeString, value)
	}
	if _u.mutation.OperatorEmailCleared() {
		_spec.ClearField(adminuseradjustment.FieldOperatorEmail, field.TypeString)
	}
	if value, ok := _u.mutation.OperatorName(); ok {
		_spec.SetField(adminuseradjustment.FieldOperatorName, field.TypeString, value)
	}
	if _u.mutation.OperatorNameCleared() {
		_spec.ClearField(adminuseradjustment.FieldOperatorName, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(adminuseradjustment.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(adminuseradjustment.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(adminuseradjustment.FieldClientIP, field.TypeString, value)
	}
	if _u.mutation.ClientIPCleared() {
		_spec.ClearField(adminuseradjustment.FieldClientIP, field.TypeString)
	}
	if value, ok := _u.mutation.AuthMethod(); ok {
		_spec.SetField(adminuseradjustment.FieldAuthMethod, field.TypeString, value)
	}
	if _u.mutation.AuthMethodCleared() {
		_spec.ClearField(adminuseradjustment.FieldAuthMethod, field.TypeString)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(adminuseradjustment.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(adminuseradjustment.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(adminuseradjustment.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.LegacyRedeemCodeID(); ok {
		_spec.SetField(adminuseradjustment.FieldLegacyRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLegacyRedeemCodeID(); ok {
		_spec.AddField(adminuseradjustment.FieldLegacyRedeemCodeID, field.TypeInt64, value)
	}
	if _u.mutation.LegacyRedeemCodeIDCleared() {
		_spec.ClearField(adminuseradjustment.FieldLegacyRedeemCodeID, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminuseradjustment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminUserAdjustmentUpdateOne is the builder for updating a single AdminUserAdjustment entity.
type AdminUserAdjustmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminUserAdjustmentMutation
}

// SetActionID sets the "action_id" field.
func (_u *AdminUserAdjustmentUpdateOne) SetActionID(v uuid.UUID) *AdminUserAdjustmentUpdateOne {
	_u.mutation.SetActionID(v)
	return _u
}

// SetNillableActionID sets the "action_id" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableActionID(v *uuid.UUID) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetActionID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *AdminUserAdjustmentUpdateOne) SetKind(v string) *AdminUserAdjustmentUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableKind(v *string) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *AdminUserAdjustmentUpdateOne) SetOperation(v string) *AdminUserAdjustmentUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableOperation(v *string) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetRequestedValue sets the "requested_value" field.
func (_u *AdminUserAdjustmentUpdateOne) SetRequestedValue(v string) *AdminUserAdjustmentUpdateOne {
	_u.mutation.SetRequestedValue(v)
	return _u
}

// SetNillableRequestedValue sets the "requested_value" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableRequestedValue(v *string) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetRequestedValue(*v)
	}
	return _u
}

// ClearRequestedValue clears the value of the "requested_value" field.
func (_u *AdminUserAdjustmentUpdateOne) ClearRequestedValue() *AdminUserAdjustmentUpdateOne {
	_u.mutation.ClearRequestedValue()
	return _u
}

// SetDelta sets the "delta" field.
func (_u *AdminUserAdjustmentUpdateOne) SetDelta(v string) *AdminUserAdjustmentUpdateOne {
	_u.mutation.SetDelta(v)
	return _u
}

// SetNillableDelta sets the "delta" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableDelta(v *string) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetDelta(*v)
	}
	return _u
}

// SetBeforeValue sets the "before_value" field.
func (_u *AdminUserAdjustmentUpdateOne) SetBeforeValue(v string) *AdminUserAdjustmentUpdateOne {
	_u.mutation.SetBeforeValue(v)
	return _u
}

// SetNillableBeforeValue sets the "before_value" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableBeforeValue(v *string) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetBeforeValue(*v)
	}
	return _u
}

// ClearBeforeValue clears the value of the "before_value" field.
func (_u *AdminUserAdjustmentUpdateOne) ClearBeforeValue() *AdminUserAdjustmentUpdateOne {
	_u.mutation.ClearBeforeValue()
	return _u
}

// SetAfterValue sets the "after_value" field.
func (_u *AdminUserAdjustmentUpdateOne) SetAfterValue(v string) *AdminUserAdjustmentUpdateOne {
	_u.mutation.SetAfterValue(v)
	return _u
}

// SetNillableAfterValue sets the "after_value" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableAfterValue(v *string) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetAfterValue(*v)
	}
	return _u
}

// ClearAfterValue clears the value of the "after_value" field.
func (_u *AdminUserAdjustmentUpdateOne) ClearAfterValue() *AdminUserAdjustmentUpdateOne {
	_u.mutation.ClearAfterValue()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AdminUserAdjustmentUpdateOne) SetUserID(v int64) *AdminUserAdjustmentUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableUserID(v *int64) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AdminUserAdjustmentUpdateOne) AddUserID(v int64) *AdminUserAdjustmentUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AdminUserAdjustmentUpdateOne) ClearUserID() *AdminUserAdjustmentUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *AdminUserAdjustmentUpdateOne) SetUserEmail(v string) *AdminUserAdjustmentUpdateOne {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableUserEmail(v *string) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// ClearUserEmail clears the value of the "user_email" field.
func (_u *AdminUserAdjustmentUpdateOne) ClearUserEmail() *AdminUserAdjustmentUpdateOne {
	_u.mutation.ClearUserEmail()
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *AdminUserAdjustmentUpdateOne) SetUserName(v string) *AdminUserAdjustmentUpdateOne {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableUserName(v *string) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// ClearUserName clears the value of the "user_name" field.
func (_u *AdminUserAdjustmentUpdateOne) ClearUserName() *AdminUserAdjustmentUpdateOne {
	_u.mutation.ClearUserName()
	return _u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *AdminUserAdjustmentUpdateOne) SetOperatorUserID(v int64) *AdminUserAdjustmentUpdateOne {
	_u.mutation.ResetOperatorUserID()
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableOperatorUserID(v *int64) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// AddOperatorUserID adds value to the "operator_user_id" field.
func (_u *AdminUserAdjustmentUpdateOne) AddOperatorUserID(v int64) *AdminUserAdjustmentUpdateOne {
	_u.mutation.AddOperatorUserID(v)
	return _u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (_u *AdminUserAdjustmentUpdateOne) ClearOperatorUserID() *AdminUserAdjustmentUpdateOne {
	_u.mutation.ClearOperatorUserID()
	return _u
}

// SetOperatorEmail sets the "operator_email" field.
func (_u *AdminUserAdjustmentUpdateOne) SetOperatorEmail(v string) *AdminUserAdjustmentUpdateOne {
	_u.mutation.SetOperatorEmail(v)
	return _u
}

// SetNillableOperatorEmail sets the "operator_email" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableOperatorEmail(v *string) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetOperatorEmail(*v)
	}
	return _u
}

// ClearOperatorEmail clears the value of the "operator_email" field.
func (_u *AdminUserAdjustmentUpdateOne) ClearOperatorEmail() *AdminUserAdjustmentUpdateOne {
	_u.mutation.ClearOperatorEmail()
	return _u
}

// SetOperatorName sets the "operator_name" field.
func (_u *AdminUserAdjustmentUpdateOne) SetOperatorName(v string) *AdminUserAdjustmentUpdateOne {
	_u.mutation.SetOperatorName(v)
	return _u
}

// SetNillableOperatorName sets the "operator_name" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableOperatorName(v *string) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetOperatorName(*v)
	}
	return _u
}

// ClearOperatorName clears the value of the "operator_name" field.
func (_u *AdminUserAdjustmentUpdateOne) ClearOperatorName() *AdminUserAdjustmentUpdateOne {
	_u.mutation.ClearOperatorName()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *AdminUserAdjustmentUpdateOne) SetNotes(v string) *AdminUserAdjustmentUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableNotes(v *string) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *AdminUserAdjustmentUpdateOne) ClearNotes() *AdminUserAdjustmentUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *AdminUserAdjustmentUpdateOne) SetClientIP(v string) *AdminUserAdjustmentUpdateOne {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableClientIP(v *string) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// ClearClientIP clears the value of the "client_ip" field.
func (_u *AdminUserAdjustmentUpdateOne) ClearClientIP() *AdminUserAdjustmentUpdateOne {
	_u.mutation.ClearClientIP()
	return _u
}

// SetAuthMethod sets the "auth_method" field.
func (_u *AdminUserAdjustmentUpdateOne) SetAuthMethod(v string) *AdminUserAdjustmentUpdateOne {
	_u.mutation.SetAuthMethod(v)
	return _u
}

// SetNillableAuthMethod sets the "auth_method" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableAuthMethod(v *string) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetAuthMethod(*v)
	}
	return _u
}

// ClearAuthMethod clears the value of the "auth_method" field.
func (_u *AdminUserAdjustmentUpdateOne) ClearAuthMethod() *AdminUserAdjustmentUpdateOne {
	_u.mutation.ClearAuthMethod()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AdminUserAdjustmentUpdateOne) SetRequestID(v string) *AdminUserAdjustmentUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableRequestID(v *string) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *AdminUserAdjustmentUpdateOne) ClearRequestID() *AdminUserAdjustmentUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetSource sets the "source" field.
func (_u *AdminUserAdjustmentUpdateOne) SetSource(v string) *AdminUserAdjustmentUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableSource(v *string) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetLegacyRedeemCodeID sets the "legacy_redeem_code_id" field.
func (_u *AdminUserAdjustmentUpdateOne) SetLegacyRedeemCodeID(v int64) *AdminUserAdjustmentUpdateOne {
	_u.mutation.ResetLegacyRedeemCodeID()
	_u.mutation.SetLegacyRedeemCodeID(v)
	return _u
}

// SetNillableLegacyRedeemCodeID sets the "legacy_redeem_code_id" field if the given value is not nil.
func (_u *AdminUserAdjustmentUpdateOne) SetNillableLegacyRedeemCodeID(v *int64) *AdminUserAdjustmentUpdateOne {
	if v != nil {
		_u.SetLegacyRedeemCodeID(*v)
	}
	return _u
}

// AddLegacyRedeemCodeID adds value to the "legacy_redeem_code_id" field.
func (_u *AdminUserAdjustmentUpdateOne) AddLegacyRedeemCodeID(v int64) *AdminUserAdjustmentUpdateOne {
	_u.mutation.AddLegacyRedeemCodeID(v)
	return _u
}

// ClearLegacyRedeemCodeID clears the value of the "legacy_redeem_code_id" field.
func (_u *AdminUserAdjustmentUpdateOne) ClearLegacyRedeemCodeID() *AdminUserAdjustmentUpdateOne {
	_u.mutation.ClearLegacyRedeemCodeID()
	return _u
}

// Mutation returns the AdminUserAdjustmentMutation object of the builder.
func (_u *AdminUserAdjustmentUpdateOne) Mutation() *AdminUserAdjustmentMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdminUserAdjustmentUpdate builder.
func (_u *AdminUserAdjustmentUpdateOne) Where(ps ...predicate.AdminUserAdjustment) *AdminUserAdjustmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminUserAdjustmentUpdateOne) Select(field string, fields ...string) *AdminUserAdjustmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminUserAdjustment entity.
func (_u *AdminUserAdjustmentUpdateOne) Save(ctx context.Context) (*AdminUserAdjustment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminUserAdjustmentUpdateOne) SaveX(ctx context.Context) *AdminUserAdjustment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminUserAdjustmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminUserAdjustmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminUserAdjustmentUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := adminuseradjustment.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operation(); ok {
		if err := adminuseradjustment.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := adminuseradjustment.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.user_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserName(); ok {
		if err := adminuseradjustment.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.user_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperatorEmail(); ok {
		if err := adminuseradjustment.OperatorEmailValidator(v); err != nil {
			return &ValidationError{Name: "operator_email", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.operator_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperatorName(); ok {
		if err := adminuseradjustment.OperatorNameValidator(v); err != nil {
			return &ValidationError{Name: "operator_name", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.operator_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientIP(); ok {
		if err := adminuseradjustment.ClientIPValidator(v); err != nil {
			return &ValidationError{Name: "client_ip", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.client_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMethod(); ok {
		if err := adminuseradjustment.AuthMethodValidator(v); err != nil {
			return &ValidationError{Name: "auth_method", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.auth_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := adminuseradjustment.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := adminuseradjustment.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.source": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminUserAdjustmentUpdateOne) sqlSave(ctx context.Context) (_node *AdminUserAdjustment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminuseradjustment.Table, adminuseradjustment.Columns, sqlgraph.NewFieldSpec(adminuseradjustment.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminUserAdjustment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminuseradjustment.FieldID)
		for _, f := range fields {
			if !adminuseradjustment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminuseradjustment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActionID(); ok {
		_spec.SetField(adminuseradjustment.FieldActionID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(adminuseradjustment.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(adminuseradjustment.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedValue(); ok {
		_spec.SetField(adminuseradjustment.FieldRequestedValue, field.TypeString, value)
	}
	if _u.mutation.RequestedValueCleared() {
		_spec.ClearField(adminuseradjustment.FieldRequestedValue, field.TypeString)
	}
	if value, ok := _u.mutation.Delta(); ok {
		_spec.SetField(adminuseradjustment.FieldDelta, field.TypeString, value)
	}
	if value, ok := _u.mutation.BeforeValue(); ok {
		_spec.SetField(adminuseradjustment.FieldBeforeValue, field.TypeString, value)
	}
	if _u.mutation.BeforeValueCleared() {
		_spec.ClearField(adminuseradjustment.FieldBeforeValue, field.TypeString)
	}
	if value, ok := _u.mutation.AfterValue(); ok {
		_spec.SetField(adminuseradjustment.FieldAfterValue, field.TypeString, value)
	}
	if _u.mutation.AfterValueCleared() {
		_spec.ClearField(adminuseradjustment.FieldAfterValue, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(adminuseradjustment.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(adminuseradjustment.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(adminuseradjustment.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(adminuseradjustment.FieldUserEmail, field.TypeString, value)
	}
	if _u.mutation.UserEmailCleared() {
		_spec.ClearField(adminuseradjustment.FieldUserEmail, field.TypeString)
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(adminuseradjustment.FieldUserName, field.TypeString, value)
	}
	if _u.mutation.UserNameCleared() {
		_spec.ClearField(adminuseradjustment.FieldUserName, field.TypeString)
	}
	if value, ok := _u.mutation.OperatorUserID(); ok {
		_spec.SetField(adminuseradjustment.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorUserID(); ok {
		_spec.AddField(adminuseradjustment.FieldOperatorUserID, field.TypeInt64, value)
	}
	if _u.mutation.OperatorUserIDCleared() {
		_spec.ClearField(adminuseradjustment.FieldOperatorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.OperatorEmail(); ok {
		_spec.SetField(adminuseradjustment.FieldOperatorEmail, field.TypeString, value)
	}
	if _u.mutation.OperatorEmailCleared() {
		_spec.ClearField(adminuseradjustment.FieldOperatorEmail, field.TypeString)
	}
	if value, ok := _u.mutation.OperatorName(); ok {
		_spec.SetField(adminuseradjustment.FieldOperatorName, field.TypeString, value)
	}
	if _u.mutation.OperatorNameCleared() {
		_spec.ClearField(adminuseradjustment.FieldOperatorName, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(adminuseradjustment.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(adminuseradjustment.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(adminuseradjustment.FieldClientIP, field.TypeString, value)
	}
	if _u.mutation.ClientIPCleared() {
		_spec.ClearField(adminuseradjustment.FieldClientIP, field.TypeString)
	}
	if value, ok := _u.mutation.AuthMethod(); ok {
		_spec.SetField(adminuseradjustment.FieldAuthMethod, field.TypeString, value)
	}
	if _u.mutation.AuthMethodCleared() {
		_spec.ClearField(adminuseradjustment.FieldAuthMethod, field.TypeString)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(adminuseradjustment.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(adminuseradjustment.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(adminuseradjustment.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.LegacyRedeemCodeID(); ok {
		_spec.SetField(adminuseradjustment.FieldLegacyRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLegacyRedeemCodeID(); ok {
		_spec.AddField(adminuseradjustment.FieldLegacyRedeemCodeID, field.TypeInt64, value)
	}
	if _u.mutation.LegacyRedeemCodeIDCleared() {
		_spec.ClearField(adminuseradjustment.FieldLegacyRedeemCodeID, field.TypeInt64)
	}
	_node = &AdminUserAdjustment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminuseradjustment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
