// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/adminuseradjustment"
	"github.com/google/uuid"
)

// AdminUserAdjustment is the model entity for the AdminUserAdjustment schema.
type AdminUserAdjustment struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ActionID holds the value of the "action_id" field.
	ActionID uuid.UUID `json:"action_id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Operation holds the value of the "operation" field.
	Operation string `json:"operation,omitempty"`
	// RequestedValue holds the value of the "requested_value" field.
	RequestedValue *string `json:"requested_value,omitempty"`
	// Delta holds the value of the "delta" field.
	Delta string `json:"delta,omitempty"`
	// BeforeValue holds the value of the "before_value" field.
	BeforeValue *string `json:"before_value,omitempty"`
	// AfterValue holds the value of the "after_value" field.
	AfterValue *string `json:"after_value,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *int64 `json:"user_id,omitempty"`
	// UserEmail holds the value of the "user_email" field.
	UserEmail *string `json:"user_email,omitempty"`
	// UserName holds the value of the "user_name" field.
	UserName *string `json:"user_name,omitempty"`
	// OperatorUserID holds the value of the "operator_user_id" field.
	OperatorUserID *int64 `json:"operator_user_id,omitempty"`
	// OperatorEmail holds the value of the "operator_email" field.
	OperatorEmail *string `json:"operator_email,omitempty"`
	// OperatorName holds the value of the "operator_name" field.
	OperatorName *string `json:"operator_name,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// ClientIP holds the value of the "client_ip" field.
	ClientIP *string `json:"client_ip,omitempty"`
	// AuthMethod holds the value of the "auth_method" field.
	AuthMethod *string `json:"auth_method,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID *string `json:"request_id,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// LegacyRedeemCodeID holds the value of the "legacy_redeem_code_id" field.
	LegacyRedeemCodeID *int64 `json:"legacy_redeem_code_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdminUserAdjustment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adminuseradjustment.FieldID, adminuseradjustment.FieldUserID, adminuseradjustment.FieldOperatorUserID, adminuseradjustment.FieldLegacyRedeemCodeID:
			values[i] = new(sql.NullInt64)
		case adminuseradjustment.FieldKind, adminuseradjustment.FieldOperation, adminuseradjustment.FieldRequestedValue, adminuseradjustment.FieldDelta, adminuseradjustment.FieldBeforeValue, adminuseradjustment.FieldAfterValue, adminuseradjustment.FieldUserEmail, adminuseradjustment.FieldUserName, adminuseradjustment.FieldOperatorEmail, adminuseradjustment.FieldOperatorName, adminuseradjustment.FieldNotes, adminuseradjustment.FieldClientIP, adminuseradjustment.FieldAuthMethod, adminuseradjustment.FieldRequestID, adminuseradjustment.FieldSource:
			values[i] = new(sql.NullString)
		case adminuseradjustment.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case adminuseradjustment.FieldActionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdminUserAdjustment fields.
func (_m *AdminUserAdjustment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adminuseradjustment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case adminuseradjustment.FieldActionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field action_id", values[i])
			} else if value != nil {
				_m.ActionID = *value
			}
		case adminuseradjustment.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case adminuseradjustment.FieldOperation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation", values[i])
			} else if value.Valid {
				_m.Operation = value.String
			}
		case adminuseradjustment.FieldRequestedValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_value", values[i])
			} else if value.Valid {
				_m.RequestedValue = new(string)
				*_m.RequestedValue = value.String
			}
		case adminuseradjustment.FieldDelta:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delta", values[i])
			} else if value.Valid {
				_m.Delta = value.String
			}
		case adminuseradjustment.FieldBeforeValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field before_value", values[i])
			} else if value.Valid {
				_m.BeforeValue = new(string)
				*_m.BeforeValue = value.String
			}
		case adminuseradjustment.FieldAfterValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field after_value", values[i])
			} else if value.Valid {
				_m.AfterValue = new(string)
				*_m.AfterValue = value.String
			}
		case adminuseradjustment.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(int64)
				*_m.UserID = value.Int64
			}
		case adminuseradjustment.FieldUserEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_email", values[i])
			} else if value.Valid {
				_m.UserEmail = new(string)
				*_m.UserEmail = value.String
			}
		case adminuseradjustment.FieldUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_name", values[i])
			} else if value.Valid {
				_m.UserName = new(string)
				*_m.UserName = value.String
			}
		case adminuseradjustment.FieldOperatorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_user_id", values[i])
			} else if value.Valid {
				_m.OperatorUserID = new(int64)
				*_m.OperatorUserID = value.Int64
			}
		case adminuseradjustment.FieldOperatorEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operator_email", values[i])
			} else if value.Valid {
				_m.OperatorEmail = new(string)
				*_m.OperatorEmail = value.String
			}
		case adminuseradjustment.FieldOperatorName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operator_name", values[i])
			} else if value.Valid {
				_m.OperatorName = new(string)
				*_m.OperatorName = value.String
			}
		case adminuseradjustment.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case adminuseradjustment.FieldClientIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_ip", values[i])
			} else if value.Valid {
				_m.ClientIP = new(string)
				*_m.ClientIP = value.String
			}
		case adminuseradjustment.FieldAuthMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_method", values[i])
			} else if value.Valid {
				_m.AuthMethod = new(string)
				*_m.AuthMethod = value.String
			}
		case adminuseradjustment.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = new(string)
				*_m.RequestID = value.String
			}
		case adminuseradjustment.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case adminuseradjustment.FieldLegacyRedeemCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field legacy_redeem_code_id", values[i])
			} else if value.Valid {
				_m.LegacyRedeemCodeID = new(int64)
				*_m.LegacyRedeemCodeID = value.Int64
			}
		case adminuseradjustment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdminUserAdjustment.
// This includes values selected through modifiers, order, etc.
func (_m *AdminUserAdjustment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AdminUserAdjustment.
// Note that you need to call AdminUserAdjustment.Unwrap() before calling this method if this AdminUserAdjustment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AdminUserAdjustment) Update() *AdminUserAdjustmentUpdateOne {
	return NewAdminUserAdjustmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AdminUserAdjustment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AdminUserAdjustment) Unwrap() *AdminUserAdjustment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdminUserAdjustment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AdminUserAdjustment) String() string {
	var builder strings.Builder
	builder.WriteString("AdminUserAdjustment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("action_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActionID))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("operation=")
	builder.WriteString(_m.Operation)
	builder.WriteString(", ")
	if v := _m.RequestedValue; v != nil {
		builder.WriteString("requested_value=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("delta=")
	builder.WriteString(_m.Delta)
	builder.WriteString(", ")
	if v := _m.BeforeValue; v != nil {
		builder.WriteString("before_value=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AfterValue; v != nil {
		builder.WriteString("after_value=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UserEmail; v != nil {
		builder.WriteString("user_email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UserName; v != nil {
		builder.WriteString("user_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OperatorUserID; v != nil {
		builder.WriteString("operator_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OperatorEmail; v != nil {
		builder.WriteString("operator_email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OperatorName; v != nil {
		builder.WriteString("operator_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ClientIP; v != nil {
		builder.WriteString("client_ip=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AuthMethod; v != nil {
		builder.WriteString("auth_method=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RequestID; v != nil {
		builder.WriteString("request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.LegacyRedeemCodeID; v != nil {
		builder.WriteString("legacy_redeem_code_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AdminUserAdjustments is a parsable slice of AdminUserAdjustment.
type AdminUserAdjustments []*AdminUserAdjustment
