// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adminuseradjustment"
	"github.com/google/uuid"
)

// AdminUserAdjustmentCreate is the builder for creating a AdminUserAdjustment entity.
type AdminUserAdjustmentCreate struct {
	config
	mutation *AdminUserAdjustmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetActionID sets the "action_id" field.
func (_c *AdminUserAdjustmentCreate) SetActionID(v uuid.UUID) *AdminUserAdjustmentCreate {
	_c.mutation.SetActionID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *AdminUserAdjustmentCreate) SetKind(v string) *AdminUserAdjustmentCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetOperation sets the "operation" field.
func (_c *AdminUserAdjustmentCreate) SetOperation(v string) *AdminUserAdjustmentCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetRequestedValue sets the "requested_value" field.
func (_c *AdminUserAdjustmentCreate) SetRequestedValue(v string) *AdminUserAdjustmentCreate {
	_c.mutation.SetRequestedValue(v)
	return _c
}

// SetNillableRequestedValue sets the "requested_value" field if the given value is not nil.
func (_c *AdminUserAdjustmentCreate) SetNillableRequestedValue(v *string) *AdminUserAdjustmentCreate {
	if v != nil {
		_c.SetRequestedValue(*v)
	}
	return _c
}

// SetDelta sets the "delta" field.
func (_c *AdminUserAdjustmentCreate) SetDelta(v string) *AdminUserAdjustmentCreate {
	_c.mutation.SetDelta(v)
	return _c
}

// SetBeforeValue sets the "before_value" field.
func (_c *AdminUserAdjustmentCreate) SetBeforeValue(v string) *AdminUserAdjustmentCreate {
	_c.mutation.SetBeforeValue(v)
	return _c
}

// SetNillableBeforeValue sets the "before_value" field if the given value is not nil.
func (_c *AdminUserAdjustmentCreate) SetNillableBeforeValue(v *string) *AdminUserAdjustmentCreate {
	if v != nil {
		_c.SetBeforeValue(*v)
	}
	return _c
}

// SetAfterValue sets the "after_value" field.
func (_c *AdminUserAdjustmentCreate) SetAfterValue(v string) *AdminUserAdjustmentCreate {
	_c.mutation.SetAfterValue(v)
	return _c
}

// SetNillableAfterValue sets the "after_value" field if the given value is not nil.
func (_c *AdminUserAdjustmentCreate) SetNillableAfterValue(v *string) *AdminUserAdjustmentCreate {
	if v != nil {
		_c.SetAfterValue(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AdminUserAdjustmentCreate) SetUserID(v int64) *AdminUserAdjustmentCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *AdminUserAdjustmentCreate) SetNillableUserID(v *int64) *AdminUserAdjustmentCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUserEmail sets the "user_email" field.
func (_c *AdminUserAdjustmentCreate) SetUserEmail(v string) *AdminUserAdjustmentCreate {
	_c.mutation.SetUserEmail(v)
	return _c
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_c *AdminUserAdjustmentCreate) SetNillableUserEmail(v *string) *AdminUserAdjustmentCreate {
	if v != nil {
		_c.SetUserEmail(*v)
	}
	return _c
}

// SetUserName sets the "user_name" field.
func (_c *AdminUserAdjustmentCreate) SetUserName(v string) *AdminUserAdjustmentCreate {
	_c.mutation.SetUserName(v)
	return _c
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_c *AdminUserAdjustmentCreate) SetNillableUserName(v *string) *AdminUserAdjustmentCreate {
	if v != nil {
		_c.SetUserName(*v)
	}
	return _c
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_c *AdminUserAdjustmentCreate) SetOperatorUserID(v int64) *AdminUserAdjustmentCreate {
	_c.mutation.SetOperatorUserID(v)
	return _c
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_c *AdminUserAdjustmentCreate) SetNillableOperatorUserID(v *int64) *AdminUserAdjustmentCreate {
	if v != nil {
		_c.SetOperatorUserID(*v)
	}
	return _c
}

// SetOperatorEmail sets the "operator_email" field.
func (_c *AdminUserAdjustmentCreate) SetOperatorEmail(v string) *AdminUserAdjustmentCreate {
	_c.mutation.SetOperatorEmail(v)
	return _c
}

// SetNillableOperatorEmail sets the "operator_email" field if the given value is not nil.
func (_c *AdminUserAdjustmentCreate) SetNillableOperatorEmail(v *string) *AdminUserAdjustmentCreate {
	if v != nil {
		_c.SetOperatorEmail(*v)
	}
	return _c
}

// SetOperatorName sets the "operator_name" field.
func (_c *AdminUserAdjustmentCreate) SetOperatorName(v string) *AdminUserAdjustmentCreate {
	_c.mutation.SetOperatorName(v)
	return _c
}

// SetNillableOperatorName sets the "operator_name" field if the given value is not nil.
func (_c *AdminUserAdjustmentCreate) SetNillableOperatorName(v *string) *AdminUserAdjustmentCreate {
	if v != nil {
		_c.SetOperatorName(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *AdminUserAdjustmentCreate) SetNotes(v string) *AdminUserAdjustmentCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *AdminUserAdjustmentCreate) SetNillableNotes(v *string) *AdminUserAdjustmentCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetClientIP sets the "client_ip" field.
func (_c *AdminUserAdjustmentCreate) SetClientIP(v string) *AdminUserAdjustmentCreate {
	_c.mutation.SetClientIP(v)
	return _c
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_c *AdminUserAdjustmentCreate) SetNillableClientIP(v *string) *AdminUserAdjustmentCreate {
	if v != nil {
		_c.SetClientIP(*v)
	}
	return _c
}

// SetAuthMethod sets the "auth_method" field.
func (_c *AdminUserAdjustmentCreate) SetAuthMethod(v string) *AdminUserAdjustmentCreate {
	_c.mutation.SetAuthMethod(v)
	return _c
}

// SetNillableAuthMethod sets the "auth_method" field if the given value is not nil.
func (_c *AdminUserAdjustmentCreate) SetNillableAuthMethod(v *string) *AdminUserAdjustmentCreate {
	if v != nil {
		_c.SetAuthMethod(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *AdminUserAdjustmentCreate) SetRequestID(v string) *AdminUserAdjustmentCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *AdminUserAdjustmentCreate) SetNillableRequestID(v *string) *AdminUserAdjustmentCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *AdminUserAdjustmentCreate) SetSource(v string) *AdminUserAdjustmentCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetLegacyRedeemCodeID sets the "legacy_redeem_code_id" field.
func (_c *AdminUserAdjustmentCreate) SetLegacyRedeemCodeID(v int64) *AdminUserAdjustmentCreate {
	_c.mutation.SetLegacyRedeemCodeID(v)
	return _c
}

// SetNillableLegacyRedeemCodeID sets the "legacy_redeem_code_id" field if the given value is not nil.
func (_c *AdminUserAdjustmentCreate) SetNillableLegacyRedeemCodeID(v *int64) *AdminUserAdjustmentCreate {
	if v != nil {
		_c.SetLegacyRedeemCodeID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdminUserAdjustmentCreate) SetCreatedAt(v time.Time) *AdminUserAdjustmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdminUserAdjustmentCreate) SetNillableCreatedAt(v *time.Time) *AdminUserAdjustmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the AdminUserAdjustmentMutation object of the builder.
func (_c *AdminUserAdjustmentCreate) Mutation() *AdminUserAdjustmentMutation {
	return _c.mutation
}

// Save creates the AdminUserAdjustment in the database.
func (_c *AdminUserAdjustmentCreate) Save(ctx context.Context) (*AdminUserAdjustment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdminUserAdjustmentCreate) SaveX(ctx context.Context) *AdminUserAdjustment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminUserAdjustmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminUserAdjustmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdminUserAdjustmentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := adminuseradjustment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdminUserAdjustmentCreate) check() error {
	if _, ok := _c.mutation.ActionID(); !ok {
		return &ValidationError{Name: "action_id", err: errors.New(`ent: missing required field "AdminUserAdjustment.action_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "AdminUserAdjustment.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := adminuseradjustment.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent: missing required field "AdminUserAdjustment.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := adminuseradjustment.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.operation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Delta(); !ok {
		return &ValidationError{Name: "delta", err: errors.New(`ent: missing required field "AdminUserAdjustment.delta"`)}
	}
	if v, ok := _c.mutation.UserEmail(); ok {
		if err := adminuseradjustment.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.user_email": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UserName(); ok {
		if err := adminuseradjustment.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.user_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OperatorEmail(); ok {
		if err := adminuseradjustment.OperatorEmailValidator(v); err != nil {
			return &ValidationError{Name: "operator_email", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.operator_email": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OperatorName(); ok {
		if err := adminuseradjustment.OperatorNameValidator(v); err != nil {
			return &ValidationError{Name: "operator_name", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.operator_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ClientIP(); ok {
		if err := adminuseradjustment.ClientIPValidator(v); err != nil {
			return &ValidationError{Name: "client_ip", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.client_ip": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AuthMethod(); ok {
		if err := adminuseradjustment.AuthMethodValidator(v); err != nil {
			return &ValidationError{Name: "auth_method", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.auth_method": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := adminuseradjustment.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "AdminUserAdjustment.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := adminuseradjustment.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "AdminUserAdjustment.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdminUserAdjustment.created_at"`)}
	}
	return nil
}

func (_c *AdminUserAdjustmentCreate) sqlSave(ctx context.Context) (*AdminUserAdjustment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdminUserAdjustmentCreate) createSpec() (*AdminUserAdjustment, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminUserAdjustment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adminuseradjustment.Table, sqlgraph.NewFieldSpec(adminuseradjustment.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ActionID(); ok {
		_spec.SetField(adminuseradjustment.FieldActionID, field.TypeUUID, value)
		_node.ActionID = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(adminuseradjustment.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(adminuseradjustment.FieldOperation, field.TypeString, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.RequestedValue(); ok {
		_spec.SetField(adminuseradjustment.FieldRequestedValue, field.TypeString, value)
		_node.RequestedValue = &value
	}
	if value, ok := _c.mutation.Delta(); ok {
		_spec.SetField(adminuseradjustment.FieldDelta, field.TypeString, value)
		_node.Delta = value
	}
	if value, ok := _c.mutation.BeforeValue(); ok {
		_spec.SetField(adminuseradjustment.FieldBeforeValue, field.TypeString, value)
		_node.BeforeValue = &value
	}
	if value, ok := _c.mutation.AfterValue(); ok {
		_spec.SetField(adminuseradjustment.FieldAfterValue, field.TypeString, value)
		_node.AfterValue = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(adminuseradjustment.FieldUserID, field.TypeInt64, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.UserEmail(); ok {
		_spec.SetField(adminuseradjustment.FieldUserEmail, field.TypeString, value)
		_node.UserEmail = &value
	}
	if value, ok := _c.mutation.UserName(); ok {
		_spec.SetField(adminuseradjustment.FieldUserName, field.TypeString, value)
		_node.UserName = &value
	}
	if value, ok := _c.mutation.OperatorUserID(); ok {
		_spec.SetField(adminuseradjustment.FieldOperatorUserID, field.TypeInt64, value)
		_node.OperatorUserID = &value
	}
	if value, ok := _c.mutation.OperatorEmail(); ok {
		_spec.SetField(adminuseradjustment.FieldOperatorEmail, field.TypeString, value)
		_node.OperatorEmail = &value
	}
	if value, ok := _c.mutation.OperatorName(); ok {
		_spec.SetField(adminuseradjustment.FieldOperatorName, field.TypeString, value)
		_node.OperatorName = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(adminuseradjustment.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.ClientIP(); ok {
		_spec.SetField(adminuseradjustment.FieldClientIP, field.TypeString, value)
		_node.ClientIP = &value
	}
	if value, ok := _c.mutation.AuthMethod(); ok {
		_spec.SetField(adminuseradjustment.FieldAuthMethod, field.TypeString, value)
		_node.AuthMethod = &value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(adminuseradjustment.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(adminuseradjustment.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.LegacyRedeemCodeID(); ok {
		_spec.SetField(adminuseradjustment.FieldLegacyRedeemCodeID, field.TypeInt64, value)
		_node.LegacyRedeemCodeID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adminuseradjustment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdminUserAdjustment.Create().
//		SetActionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdminUserAdjustmentUpsert) {
//			SetActionID(v+v).
//		}).
//		Exec(ctx)
func (_c *AdminUserAdjustmentCreate) OnConflict(opts ...sql.ConflictOption) *AdminUserAdjustmentUpsertOne {
	_c.conflict = opts
	return &AdminUserAdjustmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdminUserAdjustment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdminUserAdjustmentCreate) OnConflictColumns(columns ...string) *AdminUserAdjustmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdminUserAdjustmentUpsertOne{
		create: _c,
	}
}

type (
	// AdminUserAdjustmentUpsertOne is the builder for "upsert"-ing
	//  one AdminUserAdjustment node.
	AdminUserAdjustmentUpsertOne struct {
		create *AdminUserAdjustmentCreate
	}

	// AdminUserAdjustmentUpsert is the "OnConflict" setter.
	AdminUserAdjustmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetActionID sets the "action_id" field.
func (u *AdminUserAdjustmentUpsert) SetActionID(v uuid.UUID) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldActionID, v)
	return u
}

// UpdateActionID sets the "action_id" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateActionID() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldActionID)
	return u
}

// SetKind sets the "kind" field.
func (u *AdminUserAdjustmentUpsert) SetKind(v string) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateKind() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldKind)
	return u
}

// SetOperation sets the "operation" field.
func (u *AdminUserAdjustmentUpsert) SetOperation(v string) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldOperation, v)
	return u
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateOperation() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldOperation)
	return u
}

// SetRequestedValue sets the "requested_value" field.
func (u *AdminUserAdjustmentUpsert) SetRequestedValue(v string) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldRequestedValue, v)
	return u
}

// UpdateRequestedValue sets the "requested_value" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateRequestedValue() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldRequestedValue)
	return u
}

// ClearRequestedValue clears the value of the "requested_value" field.
func (u *AdminUserAdjustmentUpsert) ClearRequestedValue() *AdminUserAdjustmentUpsert {
	u.SetNull(adminuseradjustment.FieldRequestedValue)
	return u
}

// SetDelta sets the "delta" field.
func (u *AdminUserAdjustmentUpsert) SetDelta(v string) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldDelta, v)
	return u
}

// UpdateDelta sets the "delta" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateDelta() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldDelta)
	return u
}

// SetBeforeValue sets the "before_value" field.
func (u *AdminUserAdjustmentUpsert) SetBeforeValue(v string) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldBeforeValue, v)
	return u
}

// UpdateBeforeValue sets the "before_value" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateBeforeValue() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldBeforeValue)
	return u
}

// ClearBeforeValue clears the value of the "before_value" field.
func (u *AdminUserAdjustmentUpsert) ClearBeforeValue() *AdminUserAdjustmentUpsert {
	u.SetNull(adminuseradjustment.FieldBeforeValue)
	return u
}

// SetAfterValue sets the "after_value" field.
func (u *AdminUserAdjustmentUpsert) SetAfterValue(v string) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldAfterValue, v)
	return u
}

// UpdateAfterValue sets the "after_value" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateAfterValue() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldAfterValue)
	return u
}

// ClearAfterValue clears the value of the "after_value" field.
func (u *AdminUserAdjustmentUpsert) ClearAfterValue() *AdminUserAdjustmentUpsert {
	u.SetNull(adminuseradjustment.FieldAfterValue)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AdminUserAdjustmentUpsert) SetUserID(v int64) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateUserID() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *AdminUserAdjustmentUpsert) AddUserID(v int64) *AdminUserAdjustmentUpsert {
	u.Add(adminuseradjustment.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *AdminUserAdjustmentUpsert) ClearUserID() *AdminUserAdjustmentUpsert {
	u.SetNull(adminuseradjustment.FieldUserID)
	return u
}

// SetUserEmail sets the "user_email" field.
func (u *AdminUserAdjustmentUpsert) SetUserEmail(v string) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldUserEmail, v)
	return u
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateUserEmail() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldUserEmail)
	return u
}

// ClearUserEmail clears the value of the "user_email" field.
func (u *AdminUserAdjustmentUpsert) ClearUserEmail() *AdminUserAdjustmentUpsert {
	u.SetNull(adminuseradjustment.FieldUserEmail)
	return u
}

// SetUserName sets the "user_name" field.
func (u *AdminUserAdjustmentUpsert) SetUserName(v string) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldUserName, v)
	return u
}

// UpdateUserName sets the "user_name" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateUserName() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldUserName)
	return u
}

// ClearUserName clears the value of the "user_name" field.
func (u *AdminUserAdjustmentUpsert) ClearUserName() *AdminUserAdjustmentUpsert {
	u.SetNull(adminuseradjustment.FieldUserName)
	return u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *AdminUserAdjustmentUpsert) SetOperatorUserID(v int64) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldOperatorUserID, v)
	return u
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateOperatorUserID() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldOperatorUserID)
	return u
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *AdminUserAdjustmentUpsert) AddOperatorUserID(v int64) *AdminUserAdjustmentUpsert {
	u.Add(adminuseradjustment.FieldOperatorUserID, v)
	return u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *AdminUserAdjustmentUpsert) ClearOperatorUserID() *AdminUserAdjustmentUpsert {
	u.SetNull(adminuseradjustment.FieldOperatorUserID)
	return u
}

// SetOperatorEmail sets the "operator_email" field.
func (u *AdminUserAdjustmentUpsert) SetOperatorEmail(v string) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldOperatorEmail, v)
	return u
}

// UpdateOperatorEmail sets the "operator_email" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateOperatorEmail() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldOperatorEmail)
	return u
}

// ClearOperatorEmail clears the value of the "operator_email" field.
func (u *AdminUserAdjustmentUpsert) ClearOperatorEmail() *AdminUserAdjustmentUpsert {
	u.SetNull(adminuseradjustment.FieldOperatorEmail)
	return u
}

// SetOperatorName sets the "operator_name" field.
func (u *AdminUserAdjustmentUpsert) SetOperatorName(v string) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldOperatorName, v)
	return u
}

// UpdateOperatorName sets the "operator_name" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateOperatorName() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldOperatorName)
	return u
}

// ClearOperatorName clears the value of the "operator_name" field.
func (u *AdminUserAdjustmentUpsert) ClearOperatorName() *AdminUserAdjustmentUpsert {
	u.SetNull(adminuseradjustment.FieldOperatorName)
	return u
}

// SetNotes sets the "notes" field.
func (u *AdminUserAdjustmentUpsert) SetNotes(v string) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateNotes() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *AdminUserAdjustmentUpsert) ClearNotes() *AdminUserAdjustmentUpsert {
	u.SetNull(adminuseradjustment.FieldNotes)
	return u
}

// SetClientIP sets the "client_ip" field.
func (u *AdminUserAdjustmentUpsert) SetClientIP(v string) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldClientIP, v)
	return u
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateClientIP() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldClientIP)
	return u
}

// ClearClientIP clears the value of the "client_ip" field.
func (u *AdminUserAdjustmentUpsert) ClearClientIP() *AdminUserAdjustmentUpsert {
	u.SetNull(adminuseradjustment.FieldClientIP)
	return u
}

// SetAuthMethod sets the "auth_method" field.
func (u *AdminUserAdjustmentUpsert) SetAuthMethod(v string) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldAuthMethod, v)
	return u
}

// UpdateAuthMethod sets the "auth_method" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateAuthMethod() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldAuthMethod)
	return u
}

// ClearAuthMethod clears the value of the "auth_method" field.
func (u *AdminUserAdjustmentUpsert) ClearAuthMethod() *AdminUserAdjustmentUpsert {
	u.SetNull(adminuseradjustment.FieldAuthMethod)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *AdminUserAdjustmentUpsert) SetRequestID(v string) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateRequestID() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *AdminUserAdjustmentUpsert) ClearRequestID() *AdminUserAdjustmentUpsert {
	u.SetNull(adminuseradjustment.FieldRequestID)
	return u
}

// SetSource sets the "source" field.
func (u *AdminUserAdjustmentUpsert) SetSource(v string) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateSource() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldSource)
	return u
}

// SetLegacyRedeemCodeID sets the "legacy_redeem_code_id" field.
func (u *AdminUserAdjustmentUpsert) SetLegacyRedeemCodeID(v int64) *AdminUserAdjustmentUpsert {
	u.Set(adminuseradjustment.FieldLegacyRedeemCodeID, v)
	return u
}

// UpdateLegacyRedeemCodeID sets the "legacy_redeem_code_id" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsert) UpdateLegacyRedeemCodeID() *AdminUserAdjustmentUpsert {
	u.SetExcluded(adminuseradjustment.FieldLegacyRedeemCodeID)
	return u
}

// AddLegacyRedeemCodeID adds v to the "legacy_redeem_code_id" field.
func (u *AdminUserAdjustmentUpsert) AddLegacyRedeemCodeID(v int64) *AdminUserAdjustmentUpsert {
	u.Add(adminuseradjustment.FieldLegacyRedeemCodeID, v)
	return u
}

// ClearLegacyRedeemCodeID clears the value of the "legacy_redeem_code_id" field.
func (u *AdminUserAdjustmentUpsert) ClearLegacyRedeemCodeID() *AdminUserAdjustmentUpsert {
	u.SetNull(adminuseradjustment.FieldLegacyRedeemCodeID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AdminUserAdjustment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdminUserAdjustmentUpsertOne) UpdateNewValues() *AdminUserAdjustmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(adminuseradjustment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdminUserAdjustment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AdminUserAdjustmentUpsertOne) Ignore() *AdminUserAdjustmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdminUserAdjustmentUpsertOne) DoNothing() *AdminUserAdjustmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdminUserAdjustmentCreate.OnConflict
// documentation for more info.
func (u *AdminUserAdjustmentUpsertOne) Update(set func(*AdminUserAdjustmentUpsert)) *AdminUserAdjustmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdminUserAdjustmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetActionID sets the "action_id" field.
func (u *AdminUserAdjustmentUpsertOne) SetActionID(v uuid.UUID) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetActionID(v)
	})
}

// UpdateActionID sets the "action_id" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateActionID() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateActionID()
	})
}

// SetKind sets the "kind" field.
func (u *AdminUserAdjustmentUpsertOne) SetKind(v string) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateKind() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateKind()
	})
}

// SetOperation sets the "operation" field.
func (u *AdminUserAdjustmentUpsertOne) SetOperation(v string) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetOperation(v)
	})
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateOperation() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateOperation()
	})
}

// SetRequestedValue sets the "requested_value" field.
func (u *AdminUserAdjustmentUpsertOne) SetRequestedValue(v string) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetRequestedValue(v)
	})
}

// UpdateRequestedValue sets the "requested_value" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateRequestedValue() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateRequestedValue()
	})
}

// ClearRequestedValue clears the value of the "requested_value" field.
func (u *AdminUserAdjustmentUpsertOne) ClearRequestedValue() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearRequestedValue()
	})
}

// SetDelta sets the "delta" field.
func (u *AdminUserAdjustmentUpsertOne) SetDelta(v string) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetDelta(v)
	})
}

// UpdateDelta sets the "delta" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateDelta() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateDelta()
	})
}

// SetBeforeValue sets the "before_value" field.
func (u *AdminUserAdjustmentUpsertOne) SetBeforeValue(v string) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetBeforeValue(v)
	})
}

// UpdateBeforeValue sets the "before_value" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateBeforeValue() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateBeforeValue()
	})
}

// ClearBeforeValue clears the value of the "before_value" field.
func (u *AdminUserAdjustmentUpsertOne) ClearBeforeValue() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearBeforeValue()
	})
}

// SetAfterValue sets the "after_value" field.
func (u *AdminUserAdjustmentUpsertOne) SetAfterValue(v string) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetAfterValue(v)
	})
}

// UpdateAfterValue sets the "after_value" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateAfterValue() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateAfterValue()
	})
}

// ClearAfterValue clears the value of the "after_value" field.
func (u *AdminUserAdjustmentUpsertOne) ClearAfterValue() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearAfterValue()
	})
}

// SetUserID sets the "user_id" field.
func (u *AdminUserAdjustmentUpsertOne) SetUserID(v int64) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AdminUserAdjustmentUpsertOne) AddUserID(v int64) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateUserID() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *AdminUserAdjustmentUpsertOne) ClearUserID() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *AdminUserAdjustmentUpsertOne) SetUserEmail(v string) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateUserEmail() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateUserEmail()
	})
}

// ClearUserEmail clears the value of the "user_email" field.
func (u *AdminUserAdjustmentUpsertOne) ClearUserEmail() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearUserEmail()
	})
}

// SetUserName sets the "user_name" field.
func (u *AdminUserAdjustmentUpsertOne) SetUserName(v string) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetUserName(v)
	})
}

// UpdateUserName sets the "user_name" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateUserName() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateUserName()
	})
}

// ClearUserName clears the value of the "user_name" field.
func (u *AdminUserAdjustmentUpsertOne) ClearUserName() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearUserName()
	})
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *AdminUserAdjustmentUpsertOne) SetOperatorUserID(v int64) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetOperatorUserID(v)
	})
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *AdminUserAdjustmentUpsertOne) AddOperatorUserID(v int64) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.AddOperatorUserID(v)
	})
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateOperatorUserID() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateOperatorUserID()
	})
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *AdminUserAdjustmentUpsertOne) ClearOperatorUserID() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearOperatorUserID()
	})
}

// SetOperatorEmail sets the "operator_email" field.
func (u *AdminUserAdjustmentUpsertOne) SetOperatorEmail(v string) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetOperatorEmail(v)
	})
}

// UpdateOperatorEmail sets the "operator_email" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateOperatorEmail() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateOperatorEmail()
	})
}

// ClearOperatorEmail clears the value of the "operator_email" field.
func (u *AdminUserAdjustmentUpsertOne) ClearOperatorEmail() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearOperatorEmail()
	})
}

// SetOperatorName sets the "operator_name" field.
func (u *AdminUserAdjustmentUpsertOne) SetOperatorName(v string) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetOperatorName(v)
	})
}

// UpdateOperatorName sets the "operator_name" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateOperatorName() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateOperatorName()
	})
}

// ClearOperatorName clears the value of the "operator_name" field.
func (u *AdminUserAdjustmentUpsertOne) ClearOperatorName() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearOperatorName()
	})
}

// SetNotes sets the "notes" field.
func (u *AdminUserAdjustmentUpsertOne) SetNotes(v string) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateNotes() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *AdminUserAdjustmentUpsertOne) ClearNotes() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearNotes()
	})
}

// SetClientIP sets the "client_ip" field.
func (u *AdminUserAdjustmentUpsertOne) SetClientIP(v string) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetClientIP(v)
	})
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateClientIP() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateClientIP()
	})
}

// ClearClientIP clears the value of the "client_ip" field.
func (u *AdminUserAdjustmentUpsertOne) ClearClientIP() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearClientIP()
	})
}

// SetAuthMethod sets the "auth_method" field.
func (u *AdminUserAdjustmentUpsertOne) SetAuthMethod(v string) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetAuthMethod(v)
	})
}

// UpdateAuthMethod sets the "auth_method" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateAuthMethod() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateAuthMethod()
	})
}

// ClearAuthMethod clears the value of the "auth_method" field.
func (u *AdminUserAdjustmentUpsertOne) ClearAuthMethod() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearAuthMethod()
	})
}

// SetRequestID sets the "request_id" field.
func (u *AdminUserAdjustmentUpsertOne) SetRequestID(v string) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateRequestID() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *AdminUserAdjustmentUpsertOne) ClearRequestID() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearRequestID()
	})
}

// SetSource sets the "source" field.
func (u *AdminUserAdjustmentUpsertOne) SetSource(v string) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateSource() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateSource()
	})
}

// SetLegacyRedeemCodeID sets the "legacy_redeem_code_id" field.
func (u *AdminUserAdjustmentUpsertOne) SetLegacyRedeemCodeID(v int64) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetLegacyRedeemCodeID(v)
	})
}

// AddLegacyRedeemCodeID adds v to the "legacy_redeem_code_id" field.
func (u *AdminUserAdjustmentUpsertOne) AddLegacyRedeemCodeID(v int64) *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.AddLegacyRedeemCodeID(v)
	})
}

// UpdateLegacyRedeemCodeID sets the "legacy_redeem_code_id" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertOne) UpdateLegacyRedeemCodeID() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateLegacyRedeemCodeID()
	})
}

// ClearLegacyRedeemCodeID clears the value of the "legacy_redeem_code_id" field.
func (u *AdminUserAdjustmentUpsertOne) ClearLegacyRedeemCodeID() *AdminUserAdjustmentUpsertOne {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearLegacyRedeemCodeID()
	})
}

// Exec executes the query.
func (u *AdminUserAdjustmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdminUserAdjustmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdminUserAdjustmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AdminUserAdjustmentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AdminUserAdjustmentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AdminUserAdjustmentCreateBulk is the builder for creating many AdminUserAdjustment entities in bulk.
type AdminUserAdjustmentCreateBulk struct {
	config
	err      error
	builders []*AdminUserAdjustmentCreate
	conflict []sql.ConflictOption
}

// Save creates the AdminUserAdjustment entities in the database.
func (_c *AdminUserAdjustmentCreateBulk) Save(ctx context.Context) ([]*AdminUserAdjustment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdminUserAdjustment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminUserAdjustmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdminUserAdjustmentCreateBulk) SaveX(ctx context.Context) []*AdminUserAdjustment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminUserAdjustmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminUserAdjustmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdminUserAdjustment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdminUserAdjustmentUpsert) {
//			SetActionID(v+v).
//		}).
//		Exec(ctx)
func (_c *AdminUserAdjustmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *AdminUserAdjustmentUpsertBulk {
	_c.conflict = opts
	return &AdminUserAdjustmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdminUserAdjustment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdminUserAdjustmentCreateBulk) OnConflictColumns(columns ...string) *AdminUserAdjustmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdminUserAdjustmentUpsertBulk{
		create: _c,
	}
}

// AdminUserAdjustmentUpsertBulk is the builder for "upsert"-ing
// a bulk of AdminUserAdjustment nodes.
type AdminUserAdjustmentUpsertBulk struct {
	create *AdminUserAdjustmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AdminUserAdjustment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdminUserAdjustmentUpsertBulk) UpdateNewValues() *AdminUserAdjustmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(adminuseradjustment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdminUserAdjustment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AdminUserAdjustmentUpsertBulk) Ignore() *AdminUserAdjustmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdminUserAdjustmentUpsertBulk) DoNothing() *AdminUserAdjustmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdminUserAdjustmentCreateBulk.OnConflict
// documentation for more info.
func (u *AdminUserAdjustmentUpsertBulk) Update(set func(*AdminUserAdjustmentUpsert)) *AdminUserAdjustmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdminUserAdjustmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetActionID sets the "action_id" field.
func (u *AdminUserAdjustmentUpsertBulk) SetActionID(v uuid.UUID) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetActionID(v)
	})
}

// UpdateActionID sets the "action_id" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateActionID() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateActionID()
	})
}

// SetKind sets the "kind" field.
func (u *AdminUserAdjustmentUpsertBulk) SetKind(v string) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateKind() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateKind()
	})
}

// SetOperation sets the "operation" field.
func (u *AdminUserAdjustmentUpsertBulk) SetOperation(v string) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetOperation(v)
	})
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateOperation() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateOperation()
	})
}

// SetRequestedValue sets the "requested_value" field.
func (u *AdminUserAdjustmentUpsertBulk) SetRequestedValue(v string) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetRequestedValue(v)
	})
}

// UpdateRequestedValue sets the "requested_value" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateRequestedValue() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateRequestedValue()
	})
}

// ClearRequestedValue clears the value of the "requested_value" field.
func (u *AdminUserAdjustmentUpsertBulk) ClearRequestedValue() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearRequestedValue()
	})
}

// SetDelta sets the "delta" field.
func (u *AdminUserAdjustmentUpsertBulk) SetDelta(v string) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetDelta(v)
	})
}

// UpdateDelta sets the "delta" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateDelta() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateDelta()
	})
}

// SetBeforeValue sets the "before_value" field.
func (u *AdminUserAdjustmentUpsertBulk) SetBeforeValue(v string) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetBeforeValue(v)
	})
}

// UpdateBeforeValue sets the "before_value" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateBeforeValue() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateBeforeValue()
	})
}

// ClearBeforeValue clears the value of the "before_value" field.
func (u *AdminUserAdjustmentUpsertBulk) ClearBeforeValue() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearBeforeValue()
	})
}

// SetAfterValue sets the "after_value" field.
func (u *AdminUserAdjustmentUpsertBulk) SetAfterValue(v string) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetAfterValue(v)
	})
}

// UpdateAfterValue sets the "after_value" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateAfterValue() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateAfterValue()
	})
}

// ClearAfterValue clears the value of the "after_value" field.
func (u *AdminUserAdjustmentUpsertBulk) ClearAfterValue() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearAfterValue()
	})
}

// SetUserID sets the "user_id" field.
func (u *AdminUserAdjustmentUpsertBulk) SetUserID(v int64) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AdminUserAdjustmentUpsertBulk) AddUserID(v int64) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateUserID() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *AdminUserAdjustmentUpsertBulk) ClearUserID() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *AdminUserAdjustmentUpsertBulk) SetUserEmail(v string) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateUserEmail() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateUserEmail()
	})
}

// ClearUserEmail clears the value of the "user_email" field.
func (u *AdminUserAdjustmentUpsertBulk) ClearUserEmail() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearUserEmail()
	})
}

// SetUserName sets the "user_name" field.
func (u *AdminUserAdjustmentUpsertBulk) SetUserName(v string) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetUserName(v)
	})
}

// UpdateUserName sets the "user_name" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateUserName() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateUserName()
	})
}

// ClearUserName clears the value of the "user_name" field.
func (u *AdminUserAdjustmentUpsertBulk) ClearUserName() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearUserName()
	})
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *AdminUserAdjustmentUpsertBulk) SetOperatorUserID(v int64) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetOperatorUserID(v)
	})
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *AdminUserAdjustmentUpsertBulk) AddOperatorUserID(v int64) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.AddOperatorUserID(v)
	})
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateOperatorUserID() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateOperatorUserID()
	})
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *AdminUserAdjustmentUpsertBulk) ClearOperatorUserID() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearOperatorUserID()
	})
}

// SetOperatorEmail sets the "operator_email" field.
func (u *AdminUserAdjustmentUpsertBulk) SetOperatorEmail(v string) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetOperatorEmail(v)
	})
}

// UpdateOperatorEmail sets the "operator_email" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateOperatorEmail() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateOperatorEmail()
	})
}

// ClearOperatorEmail clears the value of the "operator_email" field.
func (u *AdminUserAdjustmentUpsertBulk) ClearOperatorEmail() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearOperatorEmail()
	})
}

// SetOperatorName sets the "operator_name" field.
func (u *AdminUserAdjustmentUpsertBulk) SetOperatorName(v string) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetOperatorName(v)
	})
}

// UpdateOperatorName sets the "operator_name" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateOperatorName() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateOperatorName()
	})
}

// ClearOperatorName clears the value of the "operator_name" field.
func (u *AdminUserAdjustmentUpsertBulk) ClearOperatorName() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearOperatorName()
	})
}

// SetNotes sets the "notes" field.
func (u *AdminUserAdjustmentUpsertBulk) SetNotes(v string) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateNotes() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *AdminUserAdjustmentUpsertBulk) ClearNotes() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearNotes()
	})
}

// SetClientIP sets the "client_ip" field.
func (u *AdminUserAdjustmentUpsertBulk) SetClientIP(v string) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetClientIP(v)
	})
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateClientIP() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateClientIP()
	})
}

// ClearClientIP clears the value of the "client_ip" field.
func (u *AdminUserAdjustmentUpsertBulk) ClearClientIP() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearClientIP()
	})
}

// SetAuthMethod sets the "auth_method" field.
func (u *AdminUserAdjustmentUpsertBulk) SetAuthMethod(v string) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetAuthMethod(v)
	})
}

// UpdateAuthMethod sets the "auth_method" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateAuthMethod() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateAuthMethod()
	})
}

// ClearAuthMethod clears the value of the "auth_method" field.
func (u *AdminUserAdjustmentUpsertBulk) ClearAuthMethod() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearAuthMethod()
	})
}

// SetRequestID sets the "request_id" field.
func (u *AdminUserAdjustmentUpsertBulk) SetRequestID(v string) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateRequestID() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *AdminUserAdjustmentUpsertBulk) ClearRequestID() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearRequestID()
	})
}

// SetSource sets the "source" field.
func (u *AdminUserAdjustmentUpsertBulk) SetSource(v string) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateSource() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateSource()
	})
}

// SetLegacyRedeemCodeID sets the "legacy_redeem_code_id" field.
func (u *AdminUserAdjustmentUpsertBulk) SetLegacyRedeemCodeID(v int64) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.SetLegacyRedeemCodeID(v)
	})
}

// AddLegacyRedeemCodeID adds v to the "legacy_redeem_code_id" field.
func (u *AdminUserAdjustmentUpsertBulk) AddLegacyRedeemCodeID(v int64) *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.AddLegacyRedeemCodeID(v)
	})
}

// UpdateLegacyRedeemCodeID sets the "legacy_redeem_code_id" field to the value that was provided on create.
func (u *AdminUserAdjustmentUpsertBulk) UpdateLegacyRedeemCodeID() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.UpdateLegacyRedeemCodeID()
	})
}

// ClearLegacyRedeemCodeID clears the value of the "legacy_redeem_code_id" field.
func (u *AdminUserAdjustmentUpsertBulk) ClearLegacyRedeemCodeID() *AdminUserAdjustmentUpsertBulk {
	return u.Update(func(s *AdminUserAdjustmentUpsert) {
		s.ClearLegacyRedeemCodeID()
	})
}

// Exec executes the query.
func (u *AdminUserAdjustmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AdminUserAdjustmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdminUserAdjustmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdminUserAdjustmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
