// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/workspace"
)

// Workspace is the model entity for the Workspace schema.
type Workspace struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// active | disabled；disabled 时该工作区成员无法登录管理端。
	Status string `json:"status,omitempty"`
	// 可增删改自己工作区的上游账号（含凭证）。
	PermAccountManage bool `json:"perm_account_manage,omitempty"`
	// 可改被授权分组的运维类字段（非计费）。
	PermGroupOps bool `json:"perm_group_ops,omitempty"`
	// 可改被授权分组的计费类字段；分组被多家共享时自动失效。
	PermGroupBilling bool `json:"perm_group_billing,omitempty"`
	// 可增删改自己工作区的代理。
	PermProxyManage bool `json:"perm_proxy_manage,omitempty"`
	// 可查看自己工作区账号的监控与统计（只读）。
	PermMonitorView bool `json:"perm_monitor_view,omitempty"`
	// 供应商可自设的账号倍率下限；NULL 表示不限下限。
	SettlementRateMin *float64 `json:"settlement_rate_min,omitempty"`
	// 供应商可自设的账号倍率上限；NULL 表示不允许供应商自改倍率。
	SettlementRateMax *float64 `json:"settlement_rate_max,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorkspaceQuery when eager-loading is set.
	Edges        WorkspaceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WorkspaceEdges holds the relations/edges for other nodes in the graph.
type WorkspaceEdges struct {
	// Members holds the value of the members edge.
	Members []*WorkspaceMember `json:"members,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) MembersOrErr() ([]*WorkspaceMember, error) {
	if e.loadedTypes[0] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Workspace) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workspace.FieldPermAccountManage, workspace.FieldPermGroupOps, workspace.FieldPermGroupBilling, workspace.FieldPermProxyManage, workspace.FieldPermMonitorView:
			values[i] = new(sql.NullBool)
		case workspace.FieldSettlementRateMin, workspace.FieldSettlementRateMax:
			values[i] = new(sql.NullFloat64)
		case workspace.FieldID:
			values[i] = new(sql.NullInt64)
		case workspace.FieldName, workspace.FieldDescription, workspace.FieldStatus:
			values[i] = new(sql.NullString)
		case workspace.FieldCreatedAt, workspace.FieldUpdatedAt, workspace.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Workspace fields.
func (_m *Workspace) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workspace.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case workspace.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case workspace.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case workspace.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case workspace.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case workspace.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case workspace.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case workspace.FieldPermAccountManage:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field perm_account_manage", values[i])
			} else if value.Valid {
				_m.PermAccountManage = value.Bool
			}
		case workspace.FieldPermGroupOps:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field perm_group_ops", values[i])
			} else if value.Valid {
				_m.PermGroupOps = value.Bool
			}
		case workspace.FieldPermGroupBilling:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field perm_group_billing", values[i])
			} else if value.Valid {
				_m.PermGroupBilling = value.Bool
			}
		case workspace.FieldPermProxyManage:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field perm_proxy_manage", values[i])
			} else if value.Valid {
				_m.PermProxyManage = value.Bool
			}
		case workspace.FieldPermMonitorView:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field perm_monitor_view", values[i])
			} else if value.Valid {
				_m.PermMonitorView = value.Bool
			}
		case workspace.FieldSettlementRateMin:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field settlement_rate_min", values[i])
			} else if value.Valid {
				_m.SettlementRateMin = new(float64)
				*_m.SettlementRateMin = value.Float64
			}
		case workspace.FieldSettlementRateMax:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field settlement_rate_max", values[i])
			} else if value.Valid {
				_m.SettlementRateMax = new(float64)
				*_m.SettlementRateMax = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Workspace.
// This includes values selected through modifiers, order, etc.
func (_m *Workspace) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMembers queries the "members" edge of the Workspace entity.
func (_m *Workspace) QueryMembers() *WorkspaceMemberQuery {
	return NewWorkspaceClient(_m.config).QueryMembers(_m)
}

// Update returns a builder for updating this Workspace.
// Note that you need to call Workspace.Unwrap() before calling this method if this Workspace
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Workspace) Update() *WorkspaceUpdateOne {
	return NewWorkspaceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Workspace entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Workspace) Unwrap() *Workspace {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Workspace is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Workspace) String() string {
	var builder strings.Builder
	builder.WriteString("Workspace(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("perm_account_manage=")
	builder.WriteString(fmt.Sprintf("%v", _m.PermAccountManage))
	builder.WriteString(", ")
	builder.WriteString("perm_group_ops=")
	builder.WriteString(fmt.Sprintf("%v", _m.PermGroupOps))
	builder.WriteString(", ")
	builder.WriteString("perm_group_billing=")
	builder.WriteString(fmt.Sprintf("%v", _m.PermGroupBilling))
	builder.WriteString(", ")
	builder.WriteString("perm_proxy_manage=")
	builder.WriteString(fmt.Sprintf("%v", _m.PermProxyManage))
	builder.WriteString(", ")
	builder.WriteString("perm_monitor_view=")
	builder.WriteString(fmt.Sprintf("%v", _m.PermMonitorView))
	builder.WriteString(", ")
	if v := _m.SettlementRateMin; v != nil {
		builder.WriteString("settlement_rate_min=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SettlementRateMax; v != nil {
		builder.WriteString("settlement_rate_max=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Workspaces is a parsable slice of Workspace.
type Workspaces []*Workspace
