// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/workspace"
	"github.com/Wei-Shaw/sub2api/ent/workspacegroupgrant"
)

// WorkspaceGroupGrantCreate is the builder for creating a WorkspaceGroupGrant entity.
type WorkspaceGroupGrantCreate struct {
	config
	mutation *WorkspaceGroupGrantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *WorkspaceGroupGrantCreate) SetWorkspaceID(v int64) *WorkspaceGroupGrantCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *WorkspaceGroupGrantCreate) SetGroupID(v int64) *WorkspaceGroupGrantCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetBasePriority sets the "base_priority" field.
func (_c *WorkspaceGroupGrantCreate) SetBasePriority(v int) *WorkspaceGroupGrantCreate {
	_c.mutation.SetBasePriority(v)
	return _c
}

// SetNillableBasePriority sets the "base_priority" field if the given value is not nil.
func (_c *WorkspaceGroupGrantCreate) SetNillableBasePriority(v *int) *WorkspaceGroupGrantCreate {
	if v != nil {
		_c.SetBasePriority(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *WorkspaceGroupGrantCreate) SetEnabled(v bool) *WorkspaceGroupGrantCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *WorkspaceGroupGrantCreate) SetNillableEnabled(v *bool) *WorkspaceGroupGrantCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WorkspaceGroupGrantCreate) SetCreatedAt(v time.Time) *WorkspaceGroupGrantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WorkspaceGroupGrantCreate) SetNillableCreatedAt(v *time.Time) *WorkspaceGroupGrantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WorkspaceGroupGrantCreate) SetUpdatedAt(v time.Time) *WorkspaceGroupGrantCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WorkspaceGroupGrantCreate) SetNillableUpdatedAt(v *time.Time) *WorkspaceGroupGrantCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_c *WorkspaceGroupGrantCreate) SetWorkspace(v *Workspace) *WorkspaceGroupGrantCreate {
	return _c.SetWorkspaceID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *WorkspaceGroupGrantCreate) SetGroup(v *Group) *WorkspaceGroupGrantCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the WorkspaceGroupGrantMutation object of the builder.
func (_c *WorkspaceGroupGrantCreate) Mutation() *WorkspaceGroupGrantMutation {
	return _c.mutation
}

// Save creates the WorkspaceGroupGrant in the database.
func (_c *WorkspaceGroupGrantCreate) Save(ctx context.Context) (*WorkspaceGroupGrant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkspaceGroupGrantCreate) SaveX(ctx context.Context) *WorkspaceGroupGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceGroupGrantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceGroupGrantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkspaceGroupGrantCreate) defaults() {
	if _, ok := _c.mutation.BasePriority(); !ok {
		v := workspacegroupgrant.DefaultBasePriority
		_c.mutation.SetBasePriority(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := workspacegroupgrant.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := workspacegroupgrant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := workspacegroupgrant.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkspaceGroupGrantCreate) check() error {
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "WorkspaceGroupGrant.workspace_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "WorkspaceGroupGrant.group_id"`)}
	}
	if _, ok := _c.mutation.BasePriority(); !ok {
		return &ValidationError{Name: "base_priority", err: errors.New(`ent: missing required field "WorkspaceGroupGrant.base_priority"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "WorkspaceGroupGrant.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WorkspaceGroupGrant.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WorkspaceGroupGrant.updated_at"`)}
	}
	if len(_c.mutation.WorkspaceIDs()) == 0 {
		return &ValidationError{Name: "workspace", err: errors.New(`ent: missing required edge "WorkspaceGroupGrant.workspace"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "WorkspaceGroupGrant.group"`)}
	}
	return nil
}

func (_c *WorkspaceGroupGrantCreate) sqlSave(ctx context.Context) (*WorkspaceGroupGrant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkspaceGroupGrantCreate) createSpec() (*WorkspaceGroupGrant, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkspaceGroupGrant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workspacegroupgrant.Table, sqlgraph.NewFieldSpec(workspacegroupgrant.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.BasePriority(); ok {
		_spec.SetField(workspacegroupgrant.FieldBasePriority, field.TypeInt, value)
		_node.BasePriority = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(workspacegroupgrant.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(workspacegroupgrant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(workspacegroupgrant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacegroupgrant.WorkspaceTable,
			Columns: []string{workspacegroupgrant.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkspaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacegroupgrant.GroupTable,
			Columns: []string{workspacegroupgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WorkspaceGroupGrant.Create().
//		SetWorkspaceID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkspaceGroupGrantUpsert) {
//			SetWorkspaceID(v+v).
//		}).
//		Exec(ctx)
func (_c *WorkspaceGroupGrantCreate) OnConflict(opts ...sql.ConflictOption) *WorkspaceGroupGrantUpsertOne {
	_c.conflict = opts
	return &WorkspaceGroupGrantUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WorkspaceGroupGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WorkspaceGroupGrantCreate) OnConflictColumns(columns ...string) *WorkspaceGroupGrantUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WorkspaceGroupGrantUpsertOne{
		create: _c,
	}
}

type (
	// WorkspaceGroupGrantUpsertOne is the builder for "upsert"-ing
	//  one WorkspaceGroupGrant node.
	WorkspaceGroupGrantUpsertOne struct {
		create *WorkspaceGroupGrantCreate
	}

	// WorkspaceGroupGrantUpsert is the "OnConflict" setter.
	WorkspaceGroupGrantUpsert struct {
		*sql.UpdateSet
	}
)

// SetWorkspaceID sets the "workspace_id" field.
func (u *WorkspaceGroupGrantUpsert) SetWorkspaceID(v int64) *WorkspaceGroupGrantUpsert {
	u.Set(workspacegroupgrant.FieldWorkspaceID, v)
	return u
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *WorkspaceGroupGrantUpsert) UpdateWorkspaceID() *WorkspaceGroupGrantUpsert {
	u.SetExcluded(workspacegroupgrant.FieldWorkspaceID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *WorkspaceGroupGrantUpsert) SetGroupID(v int64) *WorkspaceGroupGrantUpsert {
	u.Set(workspacegroupgrant.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *WorkspaceGroupGrantUpsert) UpdateGroupID() *WorkspaceGroupGrantUpsert {
	u.SetExcluded(workspacegroupgrant.FieldGroupID)
	return u
}

// SetBasePriority sets the "base_priority" field.
func (u *WorkspaceGroupGrantUpsert) SetBasePriority(v int) *WorkspaceGroupGrantUpsert {
	u.Set(workspacegroupgrant.FieldBasePriority, v)
	return u
}

// UpdateBasePriority sets the "base_priority" field to the value that was provided on create.
func (u *WorkspaceGroupGrantUpsert) UpdateBasePriority() *WorkspaceGroupGrantUpsert {
	u.SetExcluded(workspacegroupgrant.FieldBasePriority)
	return u
}

// AddBasePriority adds v to the "base_priority" field.
func (u *WorkspaceGroupGrantUpsert) AddBasePriority(v int) *WorkspaceGroupGrantUpsert {
	u.Add(workspacegroupgrant.FieldBasePriority, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *WorkspaceGroupGrantUpsert) SetEnabled(v bool) *WorkspaceGroupGrantUpsert {
	u.Set(workspacegroupgrant.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *WorkspaceGroupGrantUpsert) UpdateEnabled() *WorkspaceGroupGrantUpsert {
	u.SetExcluded(workspacegroupgrant.FieldEnabled)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkspaceGroupGrantUpsert) SetUpdatedAt(v time.Time) *WorkspaceGroupGrantUpsert {
	u.Set(workspacegroupgrant.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkspaceGroupGrantUpsert) UpdateUpdatedAt() *WorkspaceGroupGrantUpsert {
	u.SetExcluded(workspacegroupgrant.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WorkspaceGroupGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WorkspaceGroupGrantUpsertOne) UpdateNewValues() *WorkspaceGroupGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(workspacegroupgrant.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WorkspaceGroupGrant.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WorkspaceGroupGrantUpsertOne) Ignore() *WorkspaceGroupGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkspaceGroupGrantUpsertOne) DoNothing() *WorkspaceGroupGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkspaceGroupGrantCreate.OnConflict
// documentation for more info.
func (u *WorkspaceGroupGrantUpsertOne) Update(set func(*WorkspaceGroupGrantUpsert)) *WorkspaceGroupGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkspaceGroupGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *WorkspaceGroupGrantUpsertOne) SetWorkspaceID(v int64) *WorkspaceGroupGrantUpsertOne {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *WorkspaceGroupGrantUpsertOne) UpdateWorkspaceID() *WorkspaceGroupGrantUpsertOne {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.UpdateWorkspaceID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *WorkspaceGroupGrantUpsertOne) SetGroupID(v int64) *WorkspaceGroupGrantUpsertOne {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *WorkspaceGroupGrantUpsertOne) UpdateGroupID() *WorkspaceGroupGrantUpsertOne {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.UpdateGroupID()
	})
}

// SetBasePriority sets the "base_priority" field.
func (u *WorkspaceGroupGrantUpsertOne) SetBasePriority(v int) *WorkspaceGroupGrantUpsertOne {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.SetBasePriority(v)
	})
}

// AddBasePriority adds v to the "base_priority" field.
func (u *WorkspaceGroupGrantUpsertOne) AddBasePriority(v int) *WorkspaceGroupGrantUpsertOne {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.AddBasePriority(v)
	})
}

// UpdateBasePriority sets the "base_priority" field to the value that was provided on create.
func (u *WorkspaceGroupGrantUpsertOne) UpdateBasePriority() *WorkspaceGroupGrantUpsertOne {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.UpdateBasePriority()
	})
}

// SetEnabled sets the "enabled" field.
func (u *WorkspaceGroupGrantUpsertOne) SetEnabled(v bool) *WorkspaceGroupGrantUpsertOne {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *WorkspaceGroupGrantUpsertOne) UpdateEnabled() *WorkspaceGroupGrantUpsertOne {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkspaceGroupGrantUpsertOne) SetUpdatedAt(v time.Time) *WorkspaceGroupGrantUpsertOne {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkspaceGroupGrantUpsertOne) UpdateUpdatedAt() *WorkspaceGroupGrantUpsertOne {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WorkspaceGroupGrantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkspaceGroupGrantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkspaceGroupGrantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WorkspaceGroupGrantUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WorkspaceGroupGrantUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WorkspaceGroupGrantCreateBulk is the builder for creating many WorkspaceGroupGrant entities in bulk.
type WorkspaceGroupGrantCreateBulk struct {
	config
	err      error
	builders []*WorkspaceGroupGrantCreate
	conflict []sql.ConflictOption
}

// Save creates the WorkspaceGroupGrant entities in the database.
func (_c *WorkspaceGroupGrantCreateBulk) Save(ctx context.Context) ([]*WorkspaceGroupGrant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WorkspaceGroupGrant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkspaceGroupGrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkspaceGroupGrantCreateBulk) SaveX(ctx context.Context) []*WorkspaceGroupGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceGroupGrantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceGroupGrantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WorkspaceGroupGrant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkspaceGroupGrantUpsert) {
//			SetWorkspaceID(v+v).
//		}).
//		Exec(ctx)
func (_c *WorkspaceGroupGrantCreateBulk) OnConflict(opts ...sql.ConflictOption) *WorkspaceGroupGrantUpsertBulk {
	_c.conflict = opts
	return &WorkspaceGroupGrantUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WorkspaceGroupGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WorkspaceGroupGrantCreateBulk) OnConflictColumns(columns ...string) *WorkspaceGroupGrantUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WorkspaceGroupGrantUpsertBulk{
		create: _c,
	}
}

// WorkspaceGroupGrantUpsertBulk is the builder for "upsert"-ing
// a bulk of WorkspaceGroupGrant nodes.
type WorkspaceGroupGrantUpsertBulk struct {
	create *WorkspaceGroupGrantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WorkspaceGroupGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WorkspaceGroupGrantUpsertBulk) UpdateNewValues() *WorkspaceGroupGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(workspacegroupgrant.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WorkspaceGroupGrant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WorkspaceGroupGrantUpsertBulk) Ignore() *WorkspaceGroupGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkspaceGroupGrantUpsertBulk) DoNothing() *WorkspaceGroupGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkspaceGroupGrantCreateBulk.OnConflict
// documentation for more info.
func (u *WorkspaceGroupGrantUpsertBulk) Update(set func(*WorkspaceGroupGrantUpsert)) *WorkspaceGroupGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkspaceGroupGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *WorkspaceGroupGrantUpsertBulk) SetWorkspaceID(v int64) *WorkspaceGroupGrantUpsertBulk {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *WorkspaceGroupGrantUpsertBulk) UpdateWorkspaceID() *WorkspaceGroupGrantUpsertBulk {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.UpdateWorkspaceID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *WorkspaceGroupGrantUpsertBulk) SetGroupID(v int64) *WorkspaceGroupGrantUpsertBulk {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *WorkspaceGroupGrantUpsertBulk) UpdateGroupID() *WorkspaceGroupGrantUpsertBulk {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.UpdateGroupID()
	})
}

// SetBasePriority sets the "base_priority" field.
func (u *WorkspaceGroupGrantUpsertBulk) SetBasePriority(v int) *WorkspaceGroupGrantUpsertBulk {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.SetBasePriority(v)
	})
}

// AddBasePriority adds v to the "base_priority" field.
func (u *WorkspaceGroupGrantUpsertBulk) AddBasePriority(v int) *WorkspaceGroupGrantUpsertBulk {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.AddBasePriority(v)
	})
}

// UpdateBasePriority sets the "base_priority" field to the value that was provided on create.
func (u *WorkspaceGroupGrantUpsertBulk) UpdateBasePriority() *WorkspaceGroupGrantUpsertBulk {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.UpdateBasePriority()
	})
}

// SetEnabled sets the "enabled" field.
func (u *WorkspaceGroupGrantUpsertBulk) SetEnabled(v bool) *WorkspaceGroupGrantUpsertBulk {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *WorkspaceGroupGrantUpsertBulk) UpdateEnabled() *WorkspaceGroupGrantUpsertBulk {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkspaceGroupGrantUpsertBulk) SetUpdatedAt(v time.Time) *WorkspaceGroupGrantUpsertBulk {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkspaceGroupGrantUpsertBulk) UpdateUpdatedAt() *WorkspaceGroupGrantUpsertBulk {
	return u.Update(func(s *WorkspaceGroupGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WorkspaceGroupGrantUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WorkspaceGroupGrantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkspaceGroupGrantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkspaceGroupGrantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
