// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/workspace"
	"github.com/Wei-Shaw/sub2api/ent/workspacemember"
)

// WorkspaceMemberCreate is the builder for creating a WorkspaceMember entity.
type WorkspaceMemberCreate struct {
	config
	mutation *WorkspaceMemberMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *WorkspaceMemberCreate) SetUserID(v int64) *WorkspaceMemberCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *WorkspaceMemberCreate) SetWorkspaceID(v int64) *WorkspaceMemberCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WorkspaceMemberCreate) SetCreatedAt(v time.Time) *WorkspaceMemberCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WorkspaceMemberCreate) SetNillableCreatedAt(v *time.Time) *WorkspaceMemberCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *WorkspaceMemberCreate) SetUser(v *User) *WorkspaceMemberCreate {
	return _c.SetUserID(v.ID)
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_c *WorkspaceMemberCreate) SetWorkspace(v *Workspace) *WorkspaceMemberCreate {
	return _c.SetWorkspaceID(v.ID)
}

// Mutation returns the WorkspaceMemberMutation object of the builder.
func (_c *WorkspaceMemberCreate) Mutation() *WorkspaceMemberMutation {
	return _c.mutation
}

// Save creates the WorkspaceMember in the database.
func (_c *WorkspaceMemberCreate) Save(ctx context.Context) (*WorkspaceMember, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkspaceMemberCreate) SaveX(ctx context.Context) *WorkspaceMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkspaceMemberCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := workspacemember.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkspaceMemberCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "WorkspaceMember.user_id"`)}
	}
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "WorkspaceMember.workspace_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WorkspaceMember.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "WorkspaceMember.user"`)}
	}
	if len(_c.mutation.WorkspaceIDs()) == 0 {
		return &ValidationError{Name: "workspace", err: errors.New(`ent: missing required edge "WorkspaceMember.workspace"`)}
	}
	return nil
}

func (_c *WorkspaceMemberCreate) sqlSave(ctx context.Context) (*WorkspaceMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkspaceMemberCreate) createSpec() (*WorkspaceMember, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkspaceMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workspacemember.Table, sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(workspacemember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacemember.UserTable,
			Columns: []string{workspacemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacemember.WorkspaceTable,
			Columns: []string{workspacemember.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkspaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WorkspaceMember.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkspaceMemberUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *WorkspaceMemberCreate) OnConflict(opts ...sql.ConflictOption) *WorkspaceMemberUpsertOne {
	_c.conflict = opts
	return &WorkspaceMemberUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WorkspaceMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WorkspaceMemberCreate) OnConflictColumns(columns ...string) *WorkspaceMemberUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WorkspaceMemberUpsertOne{
		create: _c,
	}
}

type (
	// WorkspaceMemberUpsertOne is the builder for "upsert"-ing
	//  one WorkspaceMember node.
	WorkspaceMemberUpsertOne struct {
		create *WorkspaceMemberCreate
	}

	// WorkspaceMemberUpsert is the "OnConflict" setter.
	WorkspaceMemberUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *WorkspaceMemberUpsert) SetUserID(v int64) *WorkspaceMemberUpsert {
	u.Set(workspacemember.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WorkspaceMemberUpsert) UpdateUserID() *WorkspaceMemberUpsert {
	u.SetExcluded(workspacemember.FieldUserID)
	return u
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *WorkspaceMemberUpsert) SetWorkspaceID(v int64) *WorkspaceMemberUpsert {
	u.Set(workspacemember.FieldWorkspaceID, v)
	return u
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *WorkspaceMemberUpsert) UpdateWorkspaceID() *WorkspaceMemberUpsert {
	u.SetExcluded(workspacemember.FieldWorkspaceID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WorkspaceMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WorkspaceMemberUpsertOne) UpdateNewValues() *WorkspaceMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(workspacemember.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WorkspaceMember.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WorkspaceMemberUpsertOne) Ignore() *WorkspaceMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkspaceMemberUpsertOne) DoNothing() *WorkspaceMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkspaceMemberCreate.OnConflict
// documentation for more info.
func (u *WorkspaceMemberUpsertOne) Update(set func(*WorkspaceMemberUpsert)) *WorkspaceMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkspaceMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *WorkspaceMemberUpsertOne) SetUserID(v int64) *WorkspaceMemberUpsertOne {
	return u.Update(func(s *WorkspaceMemberUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WorkspaceMemberUpsertOne) UpdateUserID() *WorkspaceMemberUpsertOne {
	return u.Update(func(s *WorkspaceMemberUpsert) {
		s.UpdateUserID()
	})
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *WorkspaceMemberUpsertOne) SetWorkspaceID(v int64) *WorkspaceMemberUpsertOne {
	return u.Update(func(s *WorkspaceMemberUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *WorkspaceMemberUpsertOne) UpdateWorkspaceID() *WorkspaceMemberUpsertOne {
	return u.Update(func(s *WorkspaceMemberUpsert) {
		s.UpdateWorkspaceID()
	})
}

// Exec executes the query.
func (u *WorkspaceMemberUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkspaceMemberCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkspaceMemberUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WorkspaceMemberUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WorkspaceMemberUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WorkspaceMemberCreateBulk is the builder for creating many WorkspaceMember entities in bulk.
type WorkspaceMemberCreateBulk struct {
	config
	err      error
	builders []*WorkspaceMemberCreate
	conflict []sql.ConflictOption
}

// Save creates the WorkspaceMember entities in the database.
func (_c *WorkspaceMemberCreateBulk) Save(ctx context.Context) ([]*WorkspaceMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WorkspaceMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkspaceMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkspaceMemberCreateBulk) SaveX(ctx context.Context) []*WorkspaceMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WorkspaceMember.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkspaceMemberUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *WorkspaceMemberCreateBulk) OnConflict(opts ...sql.ConflictOption) *WorkspaceMemberUpsertBulk {
	_c.conflict = opts
	return &WorkspaceMemberUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WorkspaceMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WorkspaceMemberCreateBulk) OnConflictColumns(columns ...string) *WorkspaceMemberUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WorkspaceMemberUpsertBulk{
		create: _c,
	}
}

// WorkspaceMemberUpsertBulk is the builder for "upsert"-ing
// a bulk of WorkspaceMember nodes.
type WorkspaceMemberUpsertBulk struct {
	create *WorkspaceMemberCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WorkspaceMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WorkspaceMemberUpsertBulk) UpdateNewValues() *WorkspaceMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(workspacemember.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WorkspaceMember.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WorkspaceMemberUpsertBulk) Ignore() *WorkspaceMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkspaceMemberUpsertBulk) DoNothing() *WorkspaceMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkspaceMemberCreateBulk.OnConflict
// documentation for more info.
func (u *WorkspaceMemberUpsertBulk) Update(set func(*WorkspaceMemberUpsert)) *WorkspaceMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkspaceMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *WorkspaceMemberUpsertBulk) SetUserID(v int64) *WorkspaceMemberUpsertBulk {
	return u.Update(func(s *WorkspaceMemberUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WorkspaceMemberUpsertBulk) UpdateUserID() *WorkspaceMemberUpsertBulk {
	return u.Update(func(s *WorkspaceMemberUpsert) {
		s.UpdateUserID()
	})
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *WorkspaceMemberUpsertBulk) SetWorkspaceID(v int64) *WorkspaceMemberUpsertBulk {
	return u.Update(func(s *WorkspaceMemberUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *WorkspaceMemberUpsertBulk) UpdateWorkspaceID() *WorkspaceMemberUpsertBulk {
	return u.Update(func(s *WorkspaceMemberUpsert) {
		s.UpdateWorkspaceID()
	})
}

// Exec executes the query.
func (u *WorkspaceMemberUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WorkspaceMemberCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkspaceMemberCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkspaceMemberUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
