// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/workspace"
	"github.com/Wei-Shaw/sub2api/ent/workspacemember"
)

// WorkspaceCreate is the builder for creating a Workspace entity.
type WorkspaceCreate struct {
	config
	mutation *WorkspaceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *WorkspaceCreate) SetCreatedAt(v time.Time) *WorkspaceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillableCreatedAt(v *time.Time) *WorkspaceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WorkspaceCreate) SetUpdatedAt(v time.Time) *WorkspaceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillableUpdatedAt(v *time.Time) *WorkspaceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *WorkspaceCreate) SetDeletedAt(v time.Time) *WorkspaceCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillableDeletedAt(v *time.Time) *WorkspaceCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *WorkspaceCreate) SetName(v string) *WorkspaceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *WorkspaceCreate) SetDescription(v string) *WorkspaceCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillableDescription(v *string) *WorkspaceCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *WorkspaceCreate) SetStatus(v string) *WorkspaceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillableStatus(v *string) *WorkspaceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPermAccountManage sets the "perm_account_manage" field.
func (_c *WorkspaceCreate) SetPermAccountManage(v bool) *WorkspaceCreate {
	_c.mutation.SetPermAccountManage(v)
	return _c
}

// SetNillablePermAccountManage sets the "perm_account_manage" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillablePermAccountManage(v *bool) *WorkspaceCreate {
	if v != nil {
		_c.SetPermAccountManage(*v)
	}
	return _c
}

// SetPermGroupOps sets the "perm_group_ops" field.
func (_c *WorkspaceCreate) SetPermGroupOps(v bool) *WorkspaceCreate {
	_c.mutation.SetPermGroupOps(v)
	return _c
}

// SetNillablePermGroupOps sets the "perm_group_ops" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillablePermGroupOps(v *bool) *WorkspaceCreate {
	if v != nil {
		_c.SetPermGroupOps(*v)
	}
	return _c
}

// SetPermGroupBilling sets the "perm_group_billing" field.
func (_c *WorkspaceCreate) SetPermGroupBilling(v bool) *WorkspaceCreate {
	_c.mutation.SetPermGroupBilling(v)
	return _c
}

// SetNillablePermGroupBilling sets the "perm_group_billing" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillablePermGroupBilling(v *bool) *WorkspaceCreate {
	if v != nil {
		_c.SetPermGroupBilling(*v)
	}
	return _c
}

// SetPermProxyManage sets the "perm_proxy_manage" field.
func (_c *WorkspaceCreate) SetPermProxyManage(v bool) *WorkspaceCreate {
	_c.mutation.SetPermProxyManage(v)
	return _c
}

// SetNillablePermProxyManage sets the "perm_proxy_manage" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillablePermProxyManage(v *bool) *WorkspaceCreate {
	if v != nil {
		_c.SetPermProxyManage(*v)
	}
	return _c
}

// SetPermMonitorView sets the "perm_monitor_view" field.
func (_c *WorkspaceCreate) SetPermMonitorView(v bool) *WorkspaceCreate {
	_c.mutation.SetPermMonitorView(v)
	return _c
}

// SetNillablePermMonitorView sets the "perm_monitor_view" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillablePermMonitorView(v *bool) *WorkspaceCreate {
	if v != nil {
		_c.SetPermMonitorView(*v)
	}
	return _c
}

// SetSettlementRateMin sets the "settlement_rate_min" field.
func (_c *WorkspaceCreate) SetSettlementRateMin(v float64) *WorkspaceCreate {
	_c.mutation.SetSettlementRateMin(v)
	return _c
}

// SetNillableSettlementRateMin sets the "settlement_rate_min" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillableSettlementRateMin(v *float64) *WorkspaceCreate {
	if v != nil {
		_c.SetSettlementRateMin(*v)
	}
	return _c
}

// SetSettlementRateMax sets the "settlement_rate_max" field.
func (_c *WorkspaceCreate) SetSettlementRateMax(v float64) *WorkspaceCreate {
	_c.mutation.SetSettlementRateMax(v)
	return _c
}

// SetNillableSettlementRateMax sets the "settlement_rate_max" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillableSettlementRateMax(v *float64) *WorkspaceCreate {
	if v != nil {
		_c.SetSettlementRateMax(*v)
	}
	return _c
}

// AddMemberIDs adds the "members" edge to the WorkspaceMember entity by IDs.
func (_c *WorkspaceCreate) AddMemberIDs(ids ...int64) *WorkspaceCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the WorkspaceMember entity.
func (_c *WorkspaceCreate) AddMembers(v ...*WorkspaceMember) *WorkspaceCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// Mutation returns the WorkspaceMutation object of the builder.
func (_c *WorkspaceCreate) Mutation() *WorkspaceMutation {
	return _c.mutation
}

// Save creates the Workspace in the database.
func (_c *WorkspaceCreate) Save(ctx context.Context) (*Workspace, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkspaceCreate) SaveX(ctx context.Context) *Workspace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkspaceCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if workspace.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized workspace.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := workspace.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if workspace.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized workspace.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := workspace.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := workspace.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := workspace.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.PermAccountManage(); !ok {
		v := workspace.DefaultPermAccountManage
		_c.mutation.SetPermAccountManage(v)
	}
	if _, ok := _c.mutation.PermGroupOps(); !ok {
		v := workspace.DefaultPermGroupOps
		_c.mutation.SetPermGroupOps(v)
	}
	if _, ok := _c.mutation.PermGroupBilling(); !ok {
		v := workspace.DefaultPermGroupBilling
		_c.mutation.SetPermGroupBilling(v)
	}
	if _, ok := _c.mutation.PermProxyManage(); !ok {
		v := workspace.DefaultPermProxyManage
		_c.mutation.SetPermProxyManage(v)
	}
	if _, ok := _c.mutation.PermMonitorView(); !ok {
		v := workspace.DefaultPermMonitorView
		_c.mutation.SetPermMonitorView(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkspaceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Workspace.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Workspace.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Workspace.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := workspace.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Workspace.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Workspace.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := workspace.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Workspace.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Workspace.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := workspace.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Workspace.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PermAccountManage(); !ok {
		return &ValidationError{Name: "perm_account_manage", err: errors.New(`ent: missing required field "Workspace.perm_account_manage"`)}
	}
	if _, ok := _c.mutation.PermGroupOps(); !ok {
		return &ValidationError{Name: "perm_group_ops", err: errors.New(`ent: missing required field "Workspace.perm_group_ops"`)}
	}
	if _, ok := _c.mutation.PermGroupBilling(); !ok {
		return &ValidationError{Name: "perm_group_billing", err: errors.New(`ent: missing required field "Workspace.perm_group_billing"`)}
	}
	if _, ok := _c.mutation.PermProxyManage(); !ok {
		return &ValidationError{Name: "perm_proxy_manage", err: errors.New(`ent: missing required field "Workspace.perm_proxy_manage"`)}
	}
	if _, ok := _c.mutation.PermMonitorView(); !ok {
		return &ValidationError{Name: "perm_monitor_view", err: errors.New(`ent: missing required field "Workspace.perm_monitor_view"`)}
	}
	return nil
}

func (_c *WorkspaceCreate) sqlSave(ctx context.Context) (*Workspace, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkspaceCreate) createSpec() (*Workspace, *sqlgraph.CreateSpec) {
	var (
		_node = &Workspace{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workspace.Table, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(workspace.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(workspace.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(workspace.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(workspace.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(workspace.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(workspace.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PermAccountManage(); ok {
		_spec.SetField(workspace.FieldPermAccountManage, field.TypeBool, value)
		_node.PermAccountManage = value
	}
	if value, ok := _c.mutation.PermGroupOps(); ok {
		_spec.SetField(workspace.FieldPermGroupOps, field.TypeBool, value)
		_node.PermGroupOps = value
	}
	if value, ok := _c.mutation.PermGroupBilling(); ok {
		_spec.SetField(workspace.FieldPermGroupBilling, field.TypeBool, value)
		_node.PermGroupBilling = value
	}
	if value, ok := _c.mutation.PermProxyManage(); ok {
		_spec.SetField(workspace.FieldPermProxyManage, field.TypeBool, value)
		_node.PermProxyManage = value
	}
	if value, ok := _c.mutation.PermMonitorView(); ok {
		_spec.SetField(workspace.FieldPermMonitorView, field.TypeBool, value)
		_node.PermMonitorView = value
	}
	if value, ok := _c.mutation.SettlementRateMin(); ok {
		_spec.SetField(workspace.FieldSettlementRateMin, field.TypeFloat64, value)
		_node.SettlementRateMin = &value
	}
	if value, ok := _c.mutation.SettlementRateMax(); ok {
		_spec.SetField(workspace.FieldSettlementRateMax, field.TypeFloat64, value)
		_node.SettlementRateMax = &value
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.MembersTable,
			Columns: []string{workspace.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Workspace.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkspaceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WorkspaceCreate) OnConflict(opts ...sql.ConflictOption) *WorkspaceUpsertOne {
	_c.conflict = opts
	return &WorkspaceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Workspace.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WorkspaceCreate) OnConflictColumns(columns ...string) *WorkspaceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WorkspaceUpsertOne{
		create: _c,
	}
}

type (
	// WorkspaceUpsertOne is the builder for "upsert"-ing
	//  one Workspace node.
	WorkspaceUpsertOne struct {
		create *WorkspaceCreate
	}

	// WorkspaceUpsert is the "OnConflict" setter.
	WorkspaceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkspaceUpsert) SetUpdatedAt(v time.Time) *WorkspaceUpsert {
	u.Set(workspace.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkspaceUpsert) UpdateUpdatedAt() *WorkspaceUpsert {
	u.SetExcluded(workspace.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *WorkspaceUpsert) SetDeletedAt(v time.Time) *WorkspaceUpsert {
	u.Set(workspace.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *WorkspaceUpsert) UpdateDeletedAt() *WorkspaceUpsert {
	u.SetExcluded(workspace.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *WorkspaceUpsert) ClearDeletedAt() *WorkspaceUpsert {
	u.SetNull(workspace.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *WorkspaceUpsert) SetName(v string) *WorkspaceUpsert {
	u.Set(workspace.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WorkspaceUpsert) UpdateName() *WorkspaceUpsert {
	u.SetExcluded(workspace.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *WorkspaceUpsert) SetDescription(v string) *WorkspaceUpsert {
	u.Set(workspace.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *WorkspaceUpsert) UpdateDescription() *WorkspaceUpsert {
	u.SetExcluded(workspace.FieldDescription)
	return u
}

// SetStatus sets the "status" field.
func (u *WorkspaceUpsert) SetStatus(v string) *WorkspaceUpsert {
	u.Set(workspace.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WorkspaceUpsert) UpdateStatus() *WorkspaceUpsert {
	u.SetExcluded(workspace.FieldStatus)
	return u
}

// SetPermAccountManage sets the "perm_account_manage" field.
func (u *WorkspaceUpsert) SetPermAccountManage(v bool) *WorkspaceUpsert {
	u.Set(workspace.FieldPermAccountManage, v)
	return u
}

// UpdatePermAccountManage sets the "perm_account_manage" field to the value that was provided on create.
func (u *WorkspaceUpsert) UpdatePermAccountManage() *WorkspaceUpsert {
	u.SetExcluded(workspace.FieldPermAccountManage)
	return u
}

// SetPermGroupOps sets the "perm_group_ops" field.
func (u *WorkspaceUpsert) SetPermGroupOps(v bool) *WorkspaceUpsert {
	u.Set(workspace.FieldPermGroupOps, v)
	return u
}

// UpdatePermGroupOps sets the "perm_group_ops" field to the value that was provided on create.
func (u *WorkspaceUpsert) UpdatePermGroupOps() *WorkspaceUpsert {
	u.SetExcluded(workspace.FieldPermGroupOps)
	return u
}

// SetPermGroupBilling sets the "perm_group_billing" field.
func (u *WorkspaceUpsert) SetPermGroupBilling(v bool) *WorkspaceUpsert {
	u.Set(workspace.FieldPermGroupBilling, v)
	return u
}

// UpdatePermGroupBilling sets the "perm_group_billing" field to the value that was provided on create.
func (u *WorkspaceUpsert) UpdatePermGroupBilling() *WorkspaceUpsert {
	u.SetExcluded(workspace.FieldPermGroupBilling)
	return u
}

// SetPermProxyManage sets the "perm_proxy_manage" field.
func (u *WorkspaceUpsert) SetPermProxyManage(v bool) *WorkspaceUpsert {
	u.Set(workspace.FieldPermProxyManage, v)
	return u
}

// UpdatePermProxyManage sets the "perm_proxy_manage" field to the value that was provided on create.
func (u *WorkspaceUpsert) UpdatePermProxyManage() *WorkspaceUpsert {
	u.SetExcluded(workspace.FieldPermProxyManage)
	return u
}

// SetPermMonitorView sets the "perm_monitor_view" field.
func (u *WorkspaceUpsert) SetPermMonitorView(v bool) *WorkspaceUpsert {
	u.Set(workspace.FieldPermMonitorView, v)
	return u
}

// UpdatePermMonitorView sets the "perm_monitor_view" field to the value that was provided on create.
func (u *WorkspaceUpsert) UpdatePermMonitorView() *WorkspaceUpsert {
	u.SetExcluded(workspace.FieldPermMonitorView)
	return u
}

// SetSettlementRateMin sets the "settlement_rate_min" field.
func (u *WorkspaceUpsert) SetSettlementRateMin(v float64) *WorkspaceUpsert {
	u.Set(workspace.FieldSettlementRateMin, v)
	return u
}

// UpdateSettlementRateMin sets the "settlement_rate_min" field to the value that was provided on create.
func (u *WorkspaceUpsert) UpdateSettlementRateMin() *WorkspaceUpsert {
	u.SetExcluded(workspace.FieldSettlementRateMin)
	return u
}

// AddSettlementRateMin adds v to the "settlement_rate_min" field.
func (u *WorkspaceUpsert) AddSettlementRateMin(v float64) *WorkspaceUpsert {
	u.Add(workspace.FieldSettlementRateMin, v)
	return u
}

// ClearSettlementRateMin clears the value of the "settlement_rate_min" field.
func (u *WorkspaceUpsert) ClearSettlementRateMin() *WorkspaceUpsert {
	u.SetNull(workspace.FieldSettlementRateMin)
	return u
}

// SetSettlementRateMax sets the "settlement_rate_max" field.
func (u *WorkspaceUpsert) SetSettlementRateMax(v float64) *WorkspaceUpsert {
	u.Set(workspace.FieldSettlementRateMax, v)
	return u
}

// UpdateSettlementRateMax sets the "settlement_rate_max" field to the value that was provided on create.
func (u *WorkspaceUpsert) UpdateSettlementRateMax() *WorkspaceUpsert {
	u.SetExcluded(workspace.FieldSettlementRateMax)
	return u
}

// AddSettlementRateMax adds v to the "settlement_rate_max" field.
func (u *WorkspaceUpsert) AddSettlementRateMax(v float64) *WorkspaceUpsert {
	u.Add(workspace.FieldSettlementRateMax, v)
	return u
}

// ClearSettlementRateMax clears the value of the "settlement_rate_max" field.
func (u *WorkspaceUpsert) ClearSettlementRateMax() *WorkspaceUpsert {
	u.SetNull(workspace.FieldSettlementRateMax)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Workspace.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WorkspaceUpsertOne) UpdateNewValues() *WorkspaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(workspace.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Workspace.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WorkspaceUpsertOne) Ignore() *WorkspaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkspaceUpsertOne) DoNothing() *WorkspaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkspaceCreate.OnConflict
// documentation for more info.
func (u *WorkspaceUpsertOne) Update(set func(*WorkspaceUpsert)) *WorkspaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkspaceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkspaceUpsertOne) SetUpdatedAt(v time.Time) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkspaceUpsertOne) UpdateUpdatedAt() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *WorkspaceUpsertOne) SetDeletedAt(v time.Time) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *WorkspaceUpsertOne) UpdateDeletedAt() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *WorkspaceUpsertOne) ClearDeletedAt() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *WorkspaceUpsertOne) SetName(v string) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WorkspaceUpsertOne) UpdateName() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *WorkspaceUpsertOne) SetDescription(v string) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *WorkspaceUpsertOne) UpdateDescription() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateDescription()
	})
}

// SetStatus sets the "status" field.
func (u *WorkspaceUpsertOne) SetStatus(v string) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WorkspaceUpsertOne) UpdateStatus() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateStatus()
	})
}

// SetPermAccountManage sets the "perm_account_manage" field.
func (u *WorkspaceUpsertOne) SetPermAccountManage(v bool) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetPermAccountManage(v)
	})
}

// UpdatePermAccountManage sets the "perm_account_manage" field to the value that was provided on create.
func (u *WorkspaceUpsertOne) UpdatePermAccountManage() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdatePermAccountManage()
	})
}

// SetPermGroupOps sets the "perm_group_ops" field.
func (u *WorkspaceUpsertOne) SetPermGroupOps(v bool) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetPermGroupOps(v)
	})
}

// UpdatePermGroupOps sets the "perm_group_ops" field to the value that was provided on create.
func (u *WorkspaceUpsertOne) UpdatePermGroupOps() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdatePermGroupOps()
	})
}

// SetPermGroupBilling sets the "perm_group_billing" field.
func (u *WorkspaceUpsertOne) SetPermGroupBilling(v bool) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetPermGroupBilling(v)
	})
}

// UpdatePermGroupBilling sets the "perm_group_billing" field to the value that was provided on create.
func (u *WorkspaceUpsertOne) UpdatePermGroupBilling() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdatePermGroupBilling()
	})
}

// SetPermProxyManage sets the "perm_proxy_manage" field.
func (u *WorkspaceUpsertOne) SetPermProxyManage(v bool) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetPermProxyManage(v)
	})
}

// UpdatePermProxyManage sets the "perm_proxy_manage" field to the value that was provided on create.
func (u *WorkspaceUpsertOne) UpdatePermProxyManage() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdatePermProxyManage()
	})
}

// SetPermMonitorView sets the "perm_monitor_view" field.
func (u *WorkspaceUpsertOne) SetPermMonitorView(v bool) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetPermMonitorView(v)
	})
}

// UpdatePermMonitorView sets the "perm_monitor_view" field to the value that was provided on create.
func (u *WorkspaceUpsertOne) UpdatePermMonitorView() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdatePermMonitorView()
	})
}

// SetSettlementRateMin sets the "settlement_rate_min" field.
func (u *WorkspaceUpsertOne) SetSettlementRateMin(v float64) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetSettlementRateMin(v)
	})
}

// AddSettlementRateMin adds v to the "settlement_rate_min" field.
func (u *WorkspaceUpsertOne) AddSettlementRateMin(v float64) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.AddSettlementRateMin(v)
	})
}

// UpdateSettlementRateMin sets the "settlement_rate_min" field to the value that was provided on create.
func (u *WorkspaceUpsertOne) UpdateSettlementRateMin() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateSettlementRateMin()
	})
}

// ClearSettlementRateMin clears the value of the "settlement_rate_min" field.
func (u *WorkspaceUpsertOne) ClearSettlementRateMin() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.ClearSettlementRateMin()
	})
}

// SetSettlementRateMax sets the "settlement_rate_max" field.
func (u *WorkspaceUpsertOne) SetSettlementRateMax(v float64) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetSettlementRateMax(v)
	})
}

// AddSettlementRateMax adds v to the "settlement_rate_max" field.
func (u *WorkspaceUpsertOne) AddSettlementRateMax(v float64) *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.AddSettlementRateMax(v)
	})
}

// UpdateSettlementRateMax sets the "settlement_rate_max" field to the value that was provided on create.
func (u *WorkspaceUpsertOne) UpdateSettlementRateMax() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateSettlementRateMax()
	})
}

// ClearSettlementRateMax clears the value of the "settlement_rate_max" field.
func (u *WorkspaceUpsertOne) ClearSettlementRateMax() *WorkspaceUpsertOne {
	return u.Update(func(s *WorkspaceUpsert) {
		s.ClearSettlementRateMax()
	})
}

// Exec executes the query.
func (u *WorkspaceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkspaceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkspaceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WorkspaceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WorkspaceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WorkspaceCreateBulk is the builder for creating many Workspace entities in bulk.
type WorkspaceCreateBulk struct {
	config
	err      error
	builders []*WorkspaceCreate
	conflict []sql.ConflictOption
}

// Save creates the Workspace entities in the database.
func (_c *WorkspaceCreateBulk) Save(ctx context.Context) ([]*Workspace, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Workspace, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkspaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkspaceCreateBulk) SaveX(ctx context.Context) []*Workspace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Workspace.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkspaceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WorkspaceCreateBulk) OnConflict(opts ...sql.ConflictOption) *WorkspaceUpsertBulk {
	_c.conflict = opts
	return &WorkspaceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Workspace.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WorkspaceCreateBulk) OnConflictColumns(columns ...string) *WorkspaceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WorkspaceUpsertBulk{
		create: _c,
	}
}

// WorkspaceUpsertBulk is the builder for "upsert"-ing
// a bulk of Workspace nodes.
type WorkspaceUpsertBulk struct {
	create *WorkspaceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Workspace.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WorkspaceUpsertBulk) UpdateNewValues() *WorkspaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(workspace.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Workspace.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WorkspaceUpsertBulk) Ignore() *WorkspaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkspaceUpsertBulk) DoNothing() *WorkspaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkspaceCreateBulk.OnConflict
// documentation for more info.
func (u *WorkspaceUpsertBulk) Update(set func(*WorkspaceUpsert)) *WorkspaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkspaceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkspaceUpsertBulk) SetUpdatedAt(v time.Time) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkspaceUpsertBulk) UpdateUpdatedAt() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *WorkspaceUpsertBulk) SetDeletedAt(v time.Time) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *WorkspaceUpsertBulk) UpdateDeletedAt() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *WorkspaceUpsertBulk) ClearDeletedAt() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *WorkspaceUpsertBulk) SetName(v string) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WorkspaceUpsertBulk) UpdateName() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *WorkspaceUpsertBulk) SetDescription(v string) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *WorkspaceUpsertBulk) UpdateDescription() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateDescription()
	})
}

// SetStatus sets the "status" field.
func (u *WorkspaceUpsertBulk) SetStatus(v string) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WorkspaceUpsertBulk) UpdateStatus() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateStatus()
	})
}

// SetPermAccountManage sets the "perm_account_manage" field.
func (u *WorkspaceUpsertBulk) SetPermAccountManage(v bool) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetPermAccountManage(v)
	})
}

// UpdatePermAccountManage sets the "perm_account_manage" field to the value that was provided on create.
func (u *WorkspaceUpsertBulk) UpdatePermAccountManage() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdatePermAccountManage()
	})
}

// SetPermGroupOps sets the "perm_group_ops" field.
func (u *WorkspaceUpsertBulk) SetPermGroupOps(v bool) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetPermGroupOps(v)
	})
}

// UpdatePermGroupOps sets the "perm_group_ops" field to the value that was provided on create.
func (u *WorkspaceUpsertBulk) UpdatePermGroupOps() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdatePermGroupOps()
	})
}

// SetPermGroupBilling sets the "perm_group_billing" field.
func (u *WorkspaceUpsertBulk) SetPermGroupBilling(v bool) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetPermGroupBilling(v)
	})
}

// UpdatePermGroupBilling sets the "perm_group_billing" field to the value that was provided on create.
func (u *WorkspaceUpsertBulk) UpdatePermGroupBilling() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdatePermGroupBilling()
	})
}

// SetPermProxyManage sets the "perm_proxy_manage" field.
func (u *WorkspaceUpsertBulk) SetPermProxyManage(v bool) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetPermProxyManage(v)
	})
}

// UpdatePermProxyManage sets the "perm_proxy_manage" field to the value that was provided on create.
func (u *WorkspaceUpsertBulk) UpdatePermProxyManage() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdatePermProxyManage()
	})
}

// SetPermMonitorView sets the "perm_monitor_view" field.
func (u *WorkspaceUpsertBulk) SetPermMonitorView(v bool) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetPermMonitorView(v)
	})
}

// UpdatePermMonitorView sets the "perm_monitor_view" field to the value that was provided on create.
func (u *WorkspaceUpsertBulk) UpdatePermMonitorView() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdatePermMonitorView()
	})
}

// SetSettlementRateMin sets the "settlement_rate_min" field.
func (u *WorkspaceUpsertBulk) SetSettlementRateMin(v float64) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetSettlementRateMin(v)
	})
}

// AddSettlementRateMin adds v to the "settlement_rate_min" field.
func (u *WorkspaceUpsertBulk) AddSettlementRateMin(v float64) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.AddSettlementRateMin(v)
	})
}

// UpdateSettlementRateMin sets the "settlement_rate_min" field to the value that was provided on create.
func (u *WorkspaceUpsertBulk) UpdateSettlementRateMin() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateSettlementRateMin()
	})
}

// ClearSettlementRateMin clears the value of the "settlement_rate_min" field.
func (u *WorkspaceUpsertBulk) ClearSettlementRateMin() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.ClearSettlementRateMin()
	})
}

// SetSettlementRateMax sets the "settlement_rate_max" field.
func (u *WorkspaceUpsertBulk) SetSettlementRateMax(v float64) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.SetSettlementRateMax(v)
	})
}

// AddSettlementRateMax adds v to the "settlement_rate_max" field.
func (u *WorkspaceUpsertBulk) AddSettlementRateMax(v float64) *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.AddSettlementRateMax(v)
	})
}

// UpdateSettlementRateMax sets the "settlement_rate_max" field to the value that was provided on create.
func (u *WorkspaceUpsertBulk) UpdateSettlementRateMax() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.UpdateSettlementRateMax()
	})
}

// ClearSettlementRateMax clears the value of the "settlement_rate_max" field.
func (u *WorkspaceUpsertBulk) ClearSettlementRateMax() *WorkspaceUpsertBulk {
	return u.Update(func(s *WorkspaceUpsert) {
		s.ClearSettlementRateMax()
	})
}

// Exec executes the query.
func (u *WorkspaceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WorkspaceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkspaceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkspaceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
