// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/workspacegroupgrant"
)

// WorkspaceGroupGrantDelete is the builder for deleting a WorkspaceGroupGrant entity.
type WorkspaceGroupGrantDelete struct {
	config
	hooks    []Hook
	mutation *WorkspaceGroupGrantMutation
}

// Where appends a list predicates to the WorkspaceGroupGrantDelete builder.
func (_d *WorkspaceGroupGrantDelete) Where(ps ...predicate.WorkspaceGroupGrant) *WorkspaceGroupGrantDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *WorkspaceGroupGrantDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WorkspaceGroupGrantDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *WorkspaceGroupGrantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(workspacegroupgrant.Table, sqlgraph.NewFieldSpec(workspacegroupgrant.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// WorkspaceGroupGrantDeleteOne is the builder for deleting a single WorkspaceGroupGrant entity.
type WorkspaceGroupGrantDeleteOne struct {
	_d *WorkspaceGroupGrantDelete
}

// Where appends a list predicates to the WorkspaceGroupGrantDelete builder.
func (_d *WorkspaceGroupGrantDeleteOne) Where(ps ...predicate.WorkspaceGroupGrant) *WorkspaceGroupGrantDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *WorkspaceGroupGrantDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{workspacegroupgrant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WorkspaceGroupGrantDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
