// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/workspace"
	"github.com/Wei-Shaw/sub2api/ent/workspacemember"
)

// WorkspaceUpdate is the builder for updating Workspace entities.
type WorkspaceUpdate struct {
	config
	hooks    []Hook
	mutation *WorkspaceMutation
}

// Where appends a list predicates to the WorkspaceUpdate builder.
func (_u *WorkspaceUpdate) Where(ps ...predicate.Workspace) *WorkspaceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkspaceUpdate) SetUpdatedAt(v time.Time) *WorkspaceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *WorkspaceUpdate) SetDeletedAt(v time.Time) *WorkspaceUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableDeletedAt(v *time.Time) *WorkspaceUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *WorkspaceUpdate) ClearDeletedAt() *WorkspaceUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *WorkspaceUpdate) SetName(v string) *WorkspaceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableName(v *string) *WorkspaceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *WorkspaceUpdate) SetDescription(v string) *WorkspaceUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableDescription(v *string) *WorkspaceUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *WorkspaceUpdate) SetStatus(v string) *WorkspaceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableStatus(v *string) *WorkspaceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPermAccountManage sets the "perm_account_manage" field.
func (_u *WorkspaceUpdate) SetPermAccountManage(v bool) *WorkspaceUpdate {
	_u.mutation.SetPermAccountManage(v)
	return _u
}

// SetNillablePermAccountManage sets the "perm_account_manage" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillablePermAccountManage(v *bool) *WorkspaceUpdate {
	if v != nil {
		_u.SetPermAccountManage(*v)
	}
	return _u
}

// SetPermGroupOps sets the "perm_group_ops" field.
func (_u *WorkspaceUpdate) SetPermGroupOps(v bool) *WorkspaceUpdate {
	_u.mutation.SetPermGroupOps(v)
	return _u
}

// SetNillablePermGroupOps sets the "perm_group_ops" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillablePermGroupOps(v *bool) *WorkspaceUpdate {
	if v != nil {
		_u.SetPermGroupOps(*v)
	}
	return _u
}

// SetPermGroupBilling sets the "perm_group_billing" field.
func (_u *WorkspaceUpdate) SetPermGroupBilling(v bool) *WorkspaceUpdate {
	_u.mutation.SetPermGroupBilling(v)
	return _u
}

// SetNillablePermGroupBilling sets the "perm_group_billing" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillablePermGroupBilling(v *bool) *WorkspaceUpdate {
	if v != nil {
		_u.SetPermGroupBilling(*v)
	}
	return _u
}

// SetPermProxyManage sets the "perm_proxy_manage" field.
func (_u *WorkspaceUpdate) SetPermProxyManage(v bool) *WorkspaceUpdate {
	_u.mutation.SetPermProxyManage(v)
	return _u
}

// SetNillablePermProxyManage sets the "perm_proxy_manage" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillablePermProxyManage(v *bool) *WorkspaceUpdate {
	if v != nil {
		_u.SetPermProxyManage(*v)
	}
	return _u
}

// SetPermMonitorView sets the "perm_monitor_view" field.
func (_u *WorkspaceUpdate) SetPermMonitorView(v bool) *WorkspaceUpdate {
	_u.mutation.SetPermMonitorView(v)
	return _u
}

// SetNillablePermMonitorView sets the "perm_monitor_view" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillablePermMonitorView(v *bool) *WorkspaceUpdate {
	if v != nil {
		_u.SetPermMonitorView(*v)
	}
	return _u
}

// SetSettlementRateMin sets the "settlement_rate_min" field.
func (_u *WorkspaceUpdate) SetSettlementRateMin(v float64) *WorkspaceUpdate {
	_u.mutation.ResetSettlementRateMin()
	_u.mutation.SetSettlementRateMin(v)
	return _u
}

// SetNillableSettlementRateMin sets the "settlement_rate_min" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableSettlementRateMin(v *float64) *WorkspaceUpdate {
	if v != nil {
		_u.SetSettlementRateMin(*v)
	}
	return _u
}

// AddSettlementRateMin adds value to the "settlement_rate_min" field.
func (_u *WorkspaceUpdate) AddSettlementRateMin(v float64) *WorkspaceUpdate {
	_u.mutation.AddSettlementRateMin(v)
	return _u
}

// ClearSettlementRateMin clears the value of the "settlement_rate_min" field.
func (_u *WorkspaceUpdate) ClearSettlementRateMin() *WorkspaceUpdate {
	_u.mutation.ClearSettlementRateMin()
	return _u
}

// SetSettlementRateMax sets the "settlement_rate_max" field.
func (_u *WorkspaceUpdate) SetSettlementRateMax(v float64) *WorkspaceUpdate {
	_u.mutation.ResetSettlementRateMax()
	_u.mutation.SetSettlementRateMax(v)
	return _u
}

// SetNillableSettlementRateMax sets the "settlement_rate_max" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableSettlementRateMax(v *float64) *WorkspaceUpdate {
	if v != nil {
		_u.SetSettlementRateMax(*v)
	}
	return _u
}

// AddSettlementRateMax adds value to the "settlement_rate_max" field.
func (_u *WorkspaceUpdate) AddSettlementRateMax(v float64) *WorkspaceUpdate {
	_u.mutation.AddSettlementRateMax(v)
	return _u
}

// ClearSettlementRateMax clears the value of the "settlement_rate_max" field.
func (_u *WorkspaceUpdate) ClearSettlementRateMax() *WorkspaceUpdate {
	_u.mutation.ClearSettlementRateMax()
	return _u
}

// AddMemberIDs adds the "members" edge to the WorkspaceMember entity by IDs.
func (_u *WorkspaceUpdate) AddMemberIDs(ids ...int64) *WorkspaceUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the WorkspaceMember entity.
func (_u *WorkspaceUpdate) AddMembers(v ...*WorkspaceMember) *WorkspaceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the WorkspaceMutation object of the builder.
func (_u *WorkspaceUpdate) Mutation() *WorkspaceMutation {
	return _u.mutation
}

// ClearMembers clears all "members" edges to the WorkspaceMember entity.
func (_u *WorkspaceUpdate) ClearMembers() *WorkspaceUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to WorkspaceMember entities by IDs.
func (_u *WorkspaceUpdate) RemoveMemberIDs(ids ...int64) *WorkspaceUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to WorkspaceMember entities.
func (_u *WorkspaceUpdate) RemoveMembers(v ...*WorkspaceMember) *WorkspaceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkspaceUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkspaceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkspaceUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if workspace.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized workspace.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := workspace.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkspaceUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := workspace.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Workspace.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := workspace.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Workspace.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := workspace.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Workspace.status": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkspaceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspace.Table, workspace.Columns, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workspace.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(workspace.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(workspace.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(workspace.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(workspace.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(workspace.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PermAccountManage(); ok {
		_spec.SetField(workspace.FieldPermAccountManage, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PermGroupOps(); ok {
		_spec.SetField(workspace.FieldPermGroupOps, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PermGroupBilling(); ok {
		_spec.SetField(workspace.FieldPermGroupBilling, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PermProxyManage(); ok {
		_spec.SetField(workspace.FieldPermProxyManage, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PermMonitorView(); ok {
		_spec.SetField(workspace.FieldPermMonitorView, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SettlementRateMin(); ok {
		_spec.SetField(workspace.FieldSettlementRateMin, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSettlementRateMin(); ok {
		_spec.AddField(workspace.FieldSettlementRateMin, field.TypeFloat64, value)
	}
	if _u.mutation.SettlementRateMinCleared() {
		_spec.ClearField(workspace.FieldSettlementRateMin, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SettlementRateMax(); ok {
		_spec.SetField(workspace.FieldSettlementRateMax, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSettlementRateMax(); ok {
		_spec.AddField(workspace.FieldSettlementRateMax, field.TypeFloat64, value)
	}
	if _u.mutation.SettlementRateMaxCleared() {
		_spec.ClearField(workspace.FieldSettlementRateMax, field.TypeFloat64)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.MembersTable,
			Columns: []string{workspace.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.MembersTable,
			Columns: []string{workspace.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.MembersTable,
			Columns: []string{workspace.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkspaceUpdateOne is the builder for updating a single Workspace entity.
type WorkspaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkspaceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkspaceUpdateOne) SetUpdatedAt(v time.Time) *WorkspaceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *WorkspaceUpdateOne) SetDeletedAt(v time.Time) *WorkspaceUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableDeletedAt(v *time.Time) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *WorkspaceUpdateOne) ClearDeletedAt() *WorkspaceUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *WorkspaceUpdateOne) SetName(v string) *WorkspaceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableName(v *string) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *WorkspaceUpdateOne) SetDescription(v string) *WorkspaceUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableDescription(v *string) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *WorkspaceUpdateOne) SetStatus(v string) *WorkspaceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableStatus(v *string) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPermAccountManage sets the "perm_account_manage" field.
func (_u *WorkspaceUpdateOne) SetPermAccountManage(v bool) *WorkspaceUpdateOne {
	_u.mutation.SetPermAccountManage(v)
	return _u
}

// SetNillablePermAccountManage sets the "perm_account_manage" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillablePermAccountManage(v *bool) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetPermAccountManage(*v)
	}
	return _u
}

// SetPermGroupOps sets the "perm_group_ops" field.
func (_u *WorkspaceUpdateOne) SetPermGroupOps(v bool) *WorkspaceUpdateOne {
	_u.mutation.SetPermGroupOps(v)
	return _u
}

// SetNillablePermGroupOps sets the "perm_group_ops" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillablePermGroupOps(v *bool) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetPermGroupOps(*v)
	}
	return _u
}

// SetPermGroupBilling sets the "perm_group_billing" field.
func (_u *WorkspaceUpdateOne) SetPermGroupBilling(v bool) *WorkspaceUpdateOne {
	_u.mutation.SetPermGroupBilling(v)
	return _u
}

// SetNillablePermGroupBilling sets the "perm_group_billing" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillablePermGroupBilling(v *bool) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetPermGroupBilling(*v)
	}
	return _u
}

// SetPermProxyManage sets the "perm_proxy_manage" field.
func (_u *WorkspaceUpdateOne) SetPermProxyManage(v bool) *WorkspaceUpdateOne {
	_u.mutation.SetPermProxyManage(v)
	return _u
}

// SetNillablePermProxyManage sets the "perm_proxy_manage" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillablePermProxyManage(v *bool) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetPermProxyManage(*v)
	}
	return _u
}

// SetPermMonitorView sets the "perm_monitor_view" field.
func (_u *WorkspaceUpdateOne) SetPermMonitorView(v bool) *WorkspaceUpdateOne {
	_u.mutation.SetPermMonitorView(v)
	return _u
}

// SetNillablePermMonitorView sets the "perm_monitor_view" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillablePermMonitorView(v *bool) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetPermMonitorView(*v)
	}
	return _u
}

// SetSettlementRateMin sets the "settlement_rate_min" field.
func (_u *WorkspaceUpdateOne) SetSettlementRateMin(v float64) *WorkspaceUpdateOne {
	_u.mutation.ResetSettlementRateMin()
	_u.mutation.SetSettlementRateMin(v)
	return _u
}

// SetNillableSettlementRateMin sets the "settlement_rate_min" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableSettlementRateMin(v *float64) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetSettlementRateMin(*v)
	}
	return _u
}

// AddSettlementRateMin adds value to the "settlement_rate_min" field.
func (_u *WorkspaceUpdateOne) AddSettlementRateMin(v float64) *WorkspaceUpdateOne {
	_u.mutation.AddSettlementRateMin(v)
	return _u
}

// ClearSettlementRateMin clears the value of the "settlement_rate_min" field.
func (_u *WorkspaceUpdateOne) ClearSettlementRateMin() *WorkspaceUpdateOne {
	_u.mutation.ClearSettlementRateMin()
	return _u
}

// SetSettlementRateMax sets the "settlement_rate_max" field.
func (_u *WorkspaceUpdateOne) SetSettlementRateMax(v float64) *WorkspaceUpdateOne {
	_u.mutation.ResetSettlementRateMax()
	_u.mutation.SetSettlementRateMax(v)
	return _u
}

// SetNillableSettlementRateMax sets the "settlement_rate_max" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableSettlementRateMax(v *float64) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetSettlementRateMax(*v)
	}
	return _u
}

// AddSettlementRateMax adds value to the "settlement_rate_max" field.
func (_u *WorkspaceUpdateOne) AddSettlementRateMax(v float64) *WorkspaceUpdateOne {
	_u.mutation.AddSettlementRateMax(v)
	return _u
}

// ClearSettlementRateMax clears the value of the "settlement_rate_max" field.
func (_u *WorkspaceUpdateOne) ClearSettlementRateMax() *WorkspaceUpdateOne {
	_u.mutation.ClearSettlementRateMax()
	return _u
}

// AddMemberIDs adds the "members" edge to the WorkspaceMember entity by IDs.
func (_u *WorkspaceUpdateOne) AddMemberIDs(ids ...int64) *WorkspaceUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the WorkspaceMember entity.
func (_u *WorkspaceUpdateOne) AddMembers(v ...*WorkspaceMember) *WorkspaceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the WorkspaceMutation object of the builder.
func (_u *WorkspaceUpdateOne) Mutation() *WorkspaceMutation {
	return _u.mutation
}

// ClearMembers clears all "members" edges to the WorkspaceMember entity.
func (_u *WorkspaceUpdateOne) ClearMembers() *WorkspaceUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to WorkspaceMember entities by IDs.
func (_u *WorkspaceUpdateOne) RemoveMemberIDs(ids ...int64) *WorkspaceUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to WorkspaceMember entities.
func (_u *WorkspaceUpdateOne) RemoveMembers(v ...*WorkspaceMember) *WorkspaceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Where appends a list predicates to the WorkspaceUpdate builder.
func (_u *WorkspaceUpdateOne) Where(ps ...predicate.Workspace) *WorkspaceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkspaceUpdateOne) Select(field string, fields ...string) *WorkspaceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Workspace entity.
func (_u *WorkspaceUpdateOne) Save(ctx context.Context) (*Workspace, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceUpdateOne) SaveX(ctx context.Context) *Workspace {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkspaceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkspaceUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if workspace.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized workspace.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := workspace.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkspaceUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := workspace.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Workspace.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := workspace.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Workspace.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := workspace.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Workspace.status": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkspaceUpdateOne) sqlSave(ctx context.Context) (_node *Workspace, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspace.Table, workspace.Columns, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Workspace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workspace.FieldID)
		for _, f := range fields {
			if !workspace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workspace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workspace.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(workspace.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(workspace.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(workspace.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(workspace.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(workspace.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PermAccountManage(); ok {
		_spec.SetField(workspace.FieldPermAccountManage, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PermGroupOps(); ok {
		_spec.SetField(workspace.FieldPermGroupOps, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PermGroupBilling(); ok {
		_spec.SetField(workspace.FieldPermGroupBilling, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PermProxyManage(); ok {
		_spec.SetField(workspace.FieldPermProxyManage, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PermMonitorView(); ok {
		_spec.SetField(workspace.FieldPermMonitorView, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SettlementRateMin(); ok {
		_spec.SetField(workspace.FieldSettlementRateMin, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSettlementRateMin(); ok {
		_spec.AddField(workspace.FieldSettlementRateMin, field.TypeFloat64, value)
	}
	if _u.mutation.SettlementRateMinCleared() {
		_spec.ClearField(workspace.FieldSettlementRateMin, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SettlementRateMax(); ok {
		_spec.SetField(workspace.FieldSettlementRateMax, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSettlementRateMax(); ok {
		_spec.AddField(workspace.FieldSettlementRateMax, field.TypeFloat64, value)
	}
	if _u.mutation.SettlementRateMaxCleared() {
		_spec.ClearField(workspace.FieldSettlementRateMax, field.TypeFloat64)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.MembersTable,
			Columns: []string{workspace.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.MembersTable,
			Columns: []string{workspace.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.MembersTable,
			Columns: []string{workspace.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Workspace{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
