// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/workspace"
	"github.com/Wei-Shaw/sub2api/ent/workspacegroupgrant"
)

// WorkspaceGroupGrant is the model entity for the WorkspaceGroupGrant schema.
type WorkspaceGroupGrant struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID int64 `json:"workspace_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// 该供应商在此分组新增账号时强制套用的 account_groups.priority。
	BasePriority int `json:"base_priority,omitempty"`
	// 关闭后该供应商立即失去对此分组的所有操作权。
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorkspaceGroupGrantQuery when eager-loading is set.
	Edges        WorkspaceGroupGrantEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WorkspaceGroupGrantEdges holds the relations/edges for other nodes in the graph.
type WorkspaceGroupGrantEdges struct {
	// Workspace holds the value of the workspace edge.
	Workspace *Workspace `json:"workspace,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// WorkspaceOrErr returns the Workspace value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorkspaceGroupGrantEdges) WorkspaceOrErr() (*Workspace, error) {
	if e.Workspace != nil {
		return e.Workspace, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: workspace.Label}
	}
	return nil, &NotLoadedError{edge: "workspace"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorkspaceGroupGrantEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkspaceGroupGrant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workspacegroupgrant.FieldEnabled:
			values[i] = new(sql.NullBool)
		case workspacegroupgrant.FieldID, workspacegroupgrant.FieldWorkspaceID, workspacegroupgrant.FieldGroupID, workspacegroupgrant.FieldBasePriority:
			values[i] = new(sql.NullInt64)
		case workspacegroupgrant.FieldCreatedAt, workspacegroupgrant.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkspaceGroupGrant fields.
func (_m *WorkspaceGroupGrant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workspacegroupgrant.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case workspacegroupgrant.FieldWorkspaceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value.Valid {
				_m.WorkspaceID = value.Int64
			}
		case workspacegroupgrant.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case workspacegroupgrant.FieldBasePriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field base_priority", values[i])
			} else if value.Valid {
				_m.BasePriority = int(value.Int64)
			}
		case workspacegroupgrant.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case workspacegroupgrant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case workspacegroupgrant.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkspaceGroupGrant.
// This includes values selected through modifiers, order, etc.
func (_m *WorkspaceGroupGrant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWorkspace queries the "workspace" edge of the WorkspaceGroupGrant entity.
func (_m *WorkspaceGroupGrant) QueryWorkspace() *WorkspaceQuery {
	return NewWorkspaceGroupGrantClient(_m.config).QueryWorkspace(_m)
}

// QueryGroup queries the "group" edge of the WorkspaceGroupGrant entity.
func (_m *WorkspaceGroupGrant) QueryGroup() *GroupQuery {
	return NewWorkspaceGroupGrantClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this WorkspaceGroupGrant.
// Note that you need to call WorkspaceGroupGrant.Unwrap() before calling this method if this WorkspaceGroupGrant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WorkspaceGroupGrant) Update() *WorkspaceGroupGrantUpdateOne {
	return NewWorkspaceGroupGrantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WorkspaceGroupGrant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WorkspaceGroupGrant) Unwrap() *WorkspaceGroupGrant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkspaceGroupGrant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WorkspaceGroupGrant) String() string {
	var builder strings.Builder
	builder.WriteString("WorkspaceGroupGrant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("workspace_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkspaceID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("base_priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.BasePriority))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WorkspaceGroupGrants is a parsable slice of WorkspaceGroupGrant.
type WorkspaceGroupGrants []*WorkspaceGroupGrant
