// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/workspace"
	"github.com/Wei-Shaw/sub2api/ent/workspacegroupgrant"
)

// WorkspaceGroupGrantUpdate is the builder for updating WorkspaceGroupGrant entities.
type WorkspaceGroupGrantUpdate struct {
	config
	hooks    []Hook
	mutation *WorkspaceGroupGrantMutation
}

// Where appends a list predicates to the WorkspaceGroupGrantUpdate builder.
func (_u *WorkspaceGroupGrantUpdate) Where(ps ...predicate.WorkspaceGroupGrant) *WorkspaceGroupGrantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *WorkspaceGroupGrantUpdate) SetWorkspaceID(v int64) *WorkspaceGroupGrantUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *WorkspaceGroupGrantUpdate) SetNillableWorkspaceID(v *int64) *WorkspaceGroupGrantUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *WorkspaceGroupGrantUpdate) SetGroupID(v int64) *WorkspaceGroupGrantUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *WorkspaceGroupGrantUpdate) SetNillableGroupID(v *int64) *WorkspaceGroupGrantUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetBasePriority sets the "base_priority" field.
func (_u *WorkspaceGroupGrantUpdate) SetBasePriority(v int) *WorkspaceGroupGrantUpdate {
	_u.mutation.ResetBasePriority()
	_u.mutation.SetBasePriority(v)
	return _u
}

// SetNillableBasePriority sets the "base_priority" field if the given value is not nil.
func (_u *WorkspaceGroupGrantUpdate) SetNillableBasePriority(v *int) *WorkspaceGroupGrantUpdate {
	if v != nil {
		_u.SetBasePriority(*v)
	}
	return _u
}

// AddBasePriority adds value to the "base_priority" field.
func (_u *WorkspaceGroupGrantUpdate) AddBasePriority(v int) *WorkspaceGroupGrantUpdate {
	_u.mutation.AddBasePriority(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *WorkspaceGroupGrantUpdate) SetEnabled(v bool) *WorkspaceGroupGrantUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *WorkspaceGroupGrantUpdate) SetNillableEnabled(v *bool) *WorkspaceGroupGrantUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkspaceGroupGrantUpdate) SetUpdatedAt(v time.Time) *WorkspaceGroupGrantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *WorkspaceGroupGrantUpdate) SetWorkspace(v *Workspace) *WorkspaceGroupGrantUpdate {
	return _u.SetWorkspaceID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *WorkspaceGroupGrantUpdate) SetGroup(v *Group) *WorkspaceGroupGrantUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the WorkspaceGroupGrantMutation object of the builder.
func (_u *WorkspaceGroupGrantUpdate) Mutation() *WorkspaceGroupGrantMutation {
	return _u.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *WorkspaceGroupGrantUpdate) ClearWorkspace() *WorkspaceGroupGrantUpdate {
	_u.mutation.ClearWorkspace()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *WorkspaceGroupGrantUpdate) ClearGroup() *WorkspaceGroupGrantUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkspaceGroupGrantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceGroupGrantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkspaceGroupGrantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceGroupGrantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkspaceGroupGrantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workspacegroupgrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkspaceGroupGrantUpdate) check() error {
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkspaceGroupGrant.workspace"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkspaceGroupGrant.group"`)
	}
	return nil
}

func (_u *WorkspaceGroupGrantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspacegroupgrant.Table, workspacegroupgrant.Columns, sqlgraph.NewFieldSpec(workspacegroupgrant.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BasePriority(); ok {
		_spec.SetField(workspacegroupgrant.FieldBasePriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBasePriority(); ok {
		_spec.AddField(workspacegroupgrant.FieldBasePriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(workspacegroupgrant.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workspacegroupgrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacegroupgrant.WorkspaceTable,
			Columns: []string{workspacegroupgrant.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacegroupgrant.WorkspaceTable,
			Columns: []string{workspacegroupgrant.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacegroupgrant.GroupTable,
			Columns: []string{workspacegroupgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacegroupgrant.GroupTable,
			Columns: []string{workspacegroupgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspacegroupgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkspaceGroupGrantUpdateOne is the builder for updating a single WorkspaceGroupGrant entity.
type WorkspaceGroupGrantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkspaceGroupGrantMutation
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *WorkspaceGroupGrantUpdateOne) SetWorkspaceID(v int64) *WorkspaceGroupGrantUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *WorkspaceGroupGrantUpdateOne) SetNillableWorkspaceID(v *int64) *WorkspaceGroupGrantUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *WorkspaceGroupGrantUpdateOne) SetGroupID(v int64) *WorkspaceGroupGrantUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *WorkspaceGroupGrantUpdateOne) SetNillableGroupID(v *int64) *WorkspaceGroupGrantUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetBasePriority sets the "base_priority" field.
func (_u *WorkspaceGroupGrantUpdateOne) SetBasePriority(v int) *WorkspaceGroupGrantUpdateOne {
	_u.mutation.ResetBasePriority()
	_u.mutation.SetBasePriority(v)
	return _u
}

// SetNillableBasePriority sets the "base_priority" field if the given value is not nil.
func (_u *WorkspaceGroupGrantUpdateOne) SetNillableBasePriority(v *int) *WorkspaceGroupGrantUpdateOne {
	if v != nil {
		_u.SetBasePriority(*v)
	}
	return _u
}

// AddBasePriority adds value to the "base_priority" field.
func (_u *WorkspaceGroupGrantUpdateOne) AddBasePriority(v int) *WorkspaceGroupGrantUpdateOne {
	_u.mutation.AddBasePriority(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *WorkspaceGroupGrantUpdateOne) SetEnabled(v bool) *WorkspaceGroupGrantUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *WorkspaceGroupGrantUpdateOne) SetNillableEnabled(v *bool) *WorkspaceGroupGrantUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkspaceGroupGrantUpdateOne) SetUpdatedAt(v time.Time) *WorkspaceGroupGrantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *WorkspaceGroupGrantUpdateOne) SetWorkspace(v *Workspace) *WorkspaceGroupGrantUpdateOne {
	return _u.SetWorkspaceID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *WorkspaceGroupGrantUpdateOne) SetGroup(v *Group) *WorkspaceGroupGrantUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the WorkspaceGroupGrantMutation object of the builder.
func (_u *WorkspaceGroupGrantUpdateOne) Mutation() *WorkspaceGroupGrantMutation {
	return _u.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *WorkspaceGroupGrantUpdateOne) ClearWorkspace() *WorkspaceGroupGrantUpdateOne {
	_u.mutation.ClearWorkspace()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *WorkspaceGroupGrantUpdateOne) ClearGroup() *WorkspaceGroupGrantUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the WorkspaceGroupGrantUpdate builder.
func (_u *WorkspaceGroupGrantUpdateOne) Where(ps ...predicate.WorkspaceGroupGrant) *WorkspaceGroupGrantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkspaceGroupGrantUpdateOne) Select(field string, fields ...string) *WorkspaceGroupGrantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkspaceGroupGrant entity.
func (_u *WorkspaceGroupGrantUpdateOne) Save(ctx context.Context) (*WorkspaceGroupGrant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceGroupGrantUpdateOne) SaveX(ctx context.Context) *WorkspaceGroupGrant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkspaceGroupGrantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceGroupGrantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkspaceGroupGrantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workspacegroupgrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkspaceGroupGrantUpdateOne) check() error {
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkspaceGroupGrant.workspace"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkspaceGroupGrant.group"`)
	}
	return nil
}

func (_u *WorkspaceGroupGrantUpdateOne) sqlSave(ctx context.Context) (_node *WorkspaceGroupGrant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspacegroupgrant.Table, workspacegroupgrant.Columns, sqlgraph.NewFieldSpec(workspacegroupgrant.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkspaceGroupGrant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workspacegroupgrant.FieldID)
		for _, f := range fields {
			if !workspacegroupgrant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workspacegroupgrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BasePriority(); ok {
		_spec.SetField(workspacegroupgrant.FieldBasePriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBasePriority(); ok {
		_spec.AddField(workspacegroupgrant.FieldBasePriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(workspacegroupgrant.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workspacegroupgrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacegroupgrant.WorkspaceTable,
			Columns: []string{workspacegroupgrant.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacegroupgrant.WorkspaceTable,
			Columns: []string{workspacegroupgrant.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacegroupgrant.GroupTable,
			Columns: []string{workspacegroupgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacegroupgrant.GroupTable,
			Columns: []string{workspacegroupgrant.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WorkspaceGroupGrant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspacegroupgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
