// Code generated by ent, DO NOT EDIT.

package adminuseradjustment

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the adminuseradjustment type in the database.
	Label = "admin_user_adjustment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldActionID holds the string denoting the action_id field in the database.
	FieldActionID = "action_id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldRequestedValue holds the string denoting the requested_value field in the database.
	FieldRequestedValue = "requested_value"
	// FieldDelta holds the string denoting the delta field in the database.
	FieldDelta = "delta"
	// FieldBeforeValue holds the string denoting the before_value field in the database.
	FieldBeforeValue = "before_value"
	// FieldAfterValue holds the string denoting the after_value field in the database.
	FieldAfterValue = "after_value"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUserEmail holds the string denoting the user_email field in the database.
	FieldUserEmail = "user_email"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldOperatorUserID holds the string denoting the operator_user_id field in the database.
	FieldOperatorUserID = "operator_user_id"
	// FieldOperatorEmail holds the string denoting the operator_email field in the database.
	FieldOperatorEmail = "operator_email"
	// FieldOperatorName holds the string denoting the operator_name field in the database.
	FieldOperatorName = "operator_name"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldClientIP holds the string denoting the client_ip field in the database.
	FieldClientIP = "client_ip"
	// FieldAuthMethod holds the string denoting the auth_method field in the database.
	FieldAuthMethod = "auth_method"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldLegacyRedeemCodeID holds the string denoting the legacy_redeem_code_id field in the database.
	FieldLegacyRedeemCodeID = "legacy_redeem_code_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the adminuseradjustment in the database.
	Table = "admin_user_adjustments"
)

// Columns holds all SQL columns for adminuseradjustment fields.
var Columns = []string{
	FieldID,
	FieldActionID,
	FieldKind,
	FieldOperation,
	FieldRequestedValue,
	FieldDelta,
	FieldBeforeValue,
	FieldAfterValue,
	FieldUserID,
	FieldUserEmail,
	FieldUserName,
	FieldOperatorUserID,
	FieldOperatorEmail,
	FieldOperatorName,
	FieldNotes,
	FieldClientIP,
	FieldAuthMethod,
	FieldRequestID,
	FieldSource,
	FieldLegacyRedeemCodeID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// OperationValidator is a validator for the "operation" field. It is called by the builders before save.
	OperationValidator func(string) error
	// UserEmailValidator is a validator for the "user_email" field. It is called by the builders before save.
	UserEmailValidator func(string) error
	// UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	UserNameValidator func(string) error
	// OperatorEmailValidator is a validator for the "operator_email" field. It is called by the builders before save.
	OperatorEmailValidator func(string) error
	// OperatorNameValidator is a validator for the "operator_name" field. It is called by the builders before save.
	OperatorNameValidator func(string) error
	// ClientIPValidator is a validator for the "client_ip" field. It is called by the builders before save.
	ClientIPValidator func(string) error
	// AuthMethodValidator is a validator for the "auth_method" field. It is called by the builders before save.
	AuthMethodValidator func(string) error
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the AdminUserAdjustment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByActionID orders the results by the action_id field.
func ByActionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActionID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByRequestedValue orders the results by the requested_value field.
func ByRequestedValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedValue, opts...).ToFunc()
}

// ByDelta orders the results by the delta field.
func ByDelta(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDelta, opts...).ToFunc()
}

// ByBeforeValue orders the results by the before_value field.
func ByBeforeValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBeforeValue, opts...).ToFunc()
}

// ByAfterValue orders the results by the after_value field.
func ByAfterValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAfterValue, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserEmail orders the results by the user_email field.
func ByUserEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserEmail, opts...).ToFunc()
}

// ByUserName orders the results by the user_name field.
func ByUserName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserName, opts...).ToFunc()
}

// ByOperatorUserID orders the results by the operator_user_id field.
func ByOperatorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperatorUserID, opts...).ToFunc()
}

// ByOperatorEmail orders the results by the operator_email field.
func ByOperatorEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperatorEmail, opts...).ToFunc()
}

// ByOperatorName orders the results by the operator_name field.
func ByOperatorName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperatorName, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByClientIP orders the results by the client_ip field.
func ByClientIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientIP, opts...).ToFunc()
}

// ByAuthMethod orders the results by the auth_method field.
func ByAuthMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthMethod, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByLegacyRedeemCodeID orders the results by the legacy_redeem_code_id field.
func ByLegacyRedeemCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLegacyRedeemCodeID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
