// Code generated by ent, DO NOT EDIT.

package adminuseradjustment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldID, id))
}

// ActionID applies equality check predicate on the "action_id" field. It's identical to ActionIDEQ.
func ActionID(v uuid.UUID) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldActionID, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldKind, v))
}

// Operation applies equality check predicate on the "operation" field. It's identical to OperationEQ.
func Operation(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldOperation, v))
}

// RequestedValue applies equality check predicate on the "requested_value" field. It's identical to RequestedValueEQ.
func RequestedValue(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldRequestedValue, v))
}

// Delta applies equality check predicate on the "delta" field. It's identical to DeltaEQ.
func Delta(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldDelta, v))
}

// BeforeValue applies equality check predicate on the "before_value" field. It's identical to BeforeValueEQ.
func BeforeValue(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldBeforeValue, v))
}

// AfterValue applies equality check predicate on the "after_value" field. It's identical to AfterValueEQ.
func AfterValue(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldAfterValue, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldUserID, v))
}

// UserEmail applies equality check predicate on the "user_email" field. It's identical to UserEmailEQ.
func UserEmail(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldUserEmail, v))
}

// UserName applies equality check predicate on the "user_name" field. It's identical to UserNameEQ.
func UserName(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldUserName, v))
}

// OperatorUserID applies equality check predicate on the "operator_user_id" field. It's identical to OperatorUserIDEQ.
func OperatorUserID(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldOperatorUserID, v))
}

// OperatorEmail applies equality check predicate on the "operator_email" field. It's identical to OperatorEmailEQ.
func OperatorEmail(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldOperatorEmail, v))
}

// OperatorName applies equality check predicate on the "operator_name" field. It's identical to OperatorNameEQ.
func OperatorName(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldOperatorName, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldNotes, v))
}

// ClientIP applies equality check predicate on the "client_ip" field. It's identical to ClientIPEQ.
func ClientIP(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldClientIP, v))
}

// AuthMethod applies equality check predicate on the "auth_method" field. It's identical to AuthMethodEQ.
func AuthMethod(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldAuthMethod, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldRequestID, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldSource, v))
}

// LegacyRedeemCodeID applies equality check predicate on the "legacy_redeem_code_id" field. It's identical to LegacyRedeemCodeIDEQ.
func LegacyRedeemCodeID(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldLegacyRedeemCodeID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldCreatedAt, v))
}

// ActionIDEQ applies the EQ predicate on the "action_id" field.
func ActionIDEQ(v uuid.UUID) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldActionID, v))
}

// ActionIDNEQ applies the NEQ predicate on the "action_id" field.
func ActionIDNEQ(v uuid.UUID) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldActionID, v))
}

// ActionIDIn applies the In predicate on the "action_id" field.
func ActionIDIn(vs ...uuid.UUID) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldActionID, vs...))
}

// ActionIDNotIn applies the NotIn predicate on the "action_id" field.
func ActionIDNotIn(vs ...uuid.UUID) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldActionID, vs...))
}

// ActionIDGT applies the GT predicate on the "action_id" field.
func ActionIDGT(v uuid.UUID) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldActionID, v))
}

// ActionIDGTE applies the GTE predicate on the "action_id" field.
func ActionIDGTE(v uuid.UUID) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldActionID, v))
}

// ActionIDLT applies the LT predicate on the "action_id" field.
func ActionIDLT(v uuid.UUID) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldActionID, v))
}

// ActionIDLTE applies the LTE predicate on the "action_id" field.
func ActionIDLTE(v uuid.UUID) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldActionID, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContainsFold(FieldKind, v))
}

// OperationEQ applies the EQ predicate on the "operation" field.
func OperationEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldOperation, v))
}

// OperationNEQ applies the NEQ predicate on the "operation" field.
func OperationNEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldOperation, v))
}

// OperationIn applies the In predicate on the "operation" field.
func OperationIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldOperation, vs...))
}

// OperationNotIn applies the NotIn predicate on the "operation" field.
func OperationNotIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldOperation, vs...))
}

// OperationGT applies the GT predicate on the "operation" field.
func OperationGT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldOperation, v))
}

// OperationGTE applies the GTE predicate on the "operation" field.
func OperationGTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldOperation, v))
}

// OperationLT applies the LT predicate on the "operation" field.
func OperationLT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldOperation, v))
}

// OperationLTE applies the LTE predicate on the "operation" field.
func OperationLTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldOperation, v))
}

// OperationContains applies the Contains predicate on the "operation" field.
func OperationContains(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContains(FieldOperation, v))
}

// OperationHasPrefix applies the HasPrefix predicate on the "operation" field.
func OperationHasPrefix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasPrefix(FieldOperation, v))
}

// OperationHasSuffix applies the HasSuffix predicate on the "operation" field.
func OperationHasSuffix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasSuffix(FieldOperation, v))
}

// OperationEqualFold applies the EqualFold predicate on the "operation" field.
func OperationEqualFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEqualFold(FieldOperation, v))
}

// OperationContainsFold applies the ContainsFold predicate on the "operation" field.
func OperationContainsFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContainsFold(FieldOperation, v))
}

// RequestedValueEQ applies the EQ predicate on the "requested_value" field.
func RequestedValueEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldRequestedValue, v))
}

// RequestedValueNEQ applies the NEQ predicate on the "requested_value" field.
func RequestedValueNEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldRequestedValue, v))
}

// RequestedValueIn applies the In predicate on the "requested_value" field.
func RequestedValueIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldRequestedValue, vs...))
}

// RequestedValueNotIn applies the NotIn predicate on the "requested_value" field.
func RequestedValueNotIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldRequestedValue, vs...))
}

// RequestedValueGT applies the GT predicate on the "requested_value" field.
func RequestedValueGT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldRequestedValue, v))
}

// RequestedValueGTE applies the GTE predicate on the "requested_value" field.
func RequestedValueGTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldRequestedValue, v))
}

// RequestedValueLT applies the LT predicate on the "requested_value" field.
func RequestedValueLT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldRequestedValue, v))
}

// RequestedValueLTE applies the LTE predicate on the "requested_value" field.
func RequestedValueLTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldRequestedValue, v))
}

// RequestedValueContains applies the Contains predicate on the "requested_value" field.
func RequestedValueContains(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContains(FieldRequestedValue, v))
}

// RequestedValueHasPrefix applies the HasPrefix predicate on the "requested_value" field.
func RequestedValueHasPrefix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasPrefix(FieldRequestedValue, v))
}

// RequestedValueHasSuffix applies the HasSuffix predicate on the "requested_value" field.
func RequestedValueHasSuffix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasSuffix(FieldRequestedValue, v))
}

// RequestedValueIsNil applies the IsNil predicate on the "requested_value" field.
func RequestedValueIsNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIsNull(FieldRequestedValue))
}

// RequestedValueNotNil applies the NotNil predicate on the "requested_value" field.
func RequestedValueNotNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotNull(FieldRequestedValue))
}

// RequestedValueEqualFold applies the EqualFold predicate on the "requested_value" field.
func RequestedValueEqualFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEqualFold(FieldRequestedValue, v))
}

// RequestedValueContainsFold applies the ContainsFold predicate on the "requested_value" field.
func RequestedValueContainsFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContainsFold(FieldRequestedValue, v))
}

// DeltaEQ applies the EQ predicate on the "delta" field.
func DeltaEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldDelta, v))
}

// DeltaNEQ applies the NEQ predicate on the "delta" field.
func DeltaNEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldDelta, v))
}

// DeltaIn applies the In predicate on the "delta" field.
func DeltaIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldDelta, vs...))
}

// DeltaNotIn applies the NotIn predicate on the "delta" field.
func DeltaNotIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldDelta, vs...))
}

// DeltaGT applies the GT predicate on the "delta" field.
func DeltaGT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldDelta, v))
}

// DeltaGTE applies the GTE predicate on the "delta" field.
func DeltaGTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldDelta, v))
}

// DeltaLT applies the LT predicate on the "delta" field.
func DeltaLT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldDelta, v))
}

// DeltaLTE applies the LTE predicate on the "delta" field.
func DeltaLTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldDelta, v))
}

// DeltaContains applies the Contains predicate on the "delta" field.
func DeltaContains(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContains(FieldDelta, v))
}

// DeltaHasPrefix applies the HasPrefix predicate on the "delta" field.
func DeltaHasPrefix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasPrefix(FieldDelta, v))
}

// DeltaHasSuffix applies the HasSuffix predicate on the "delta" field.
func DeltaHasSuffix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasSuffix(FieldDelta, v))
}

// DeltaEqualFold applies the EqualFold predicate on the "delta" field.
func DeltaEqualFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEqualFold(FieldDelta, v))
}

// DeltaContainsFold applies the ContainsFold predicate on the "delta" field.
func DeltaContainsFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContainsFold(FieldDelta, v))
}

// BeforeValueEQ applies the EQ predicate on the "before_value" field.
func BeforeValueEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldBeforeValue, v))
}

// BeforeValueNEQ applies the NEQ predicate on the "before_value" field.
func BeforeValueNEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldBeforeValue, v))
}

// BeforeValueIn applies the In predicate on the "before_value" field.
func BeforeValueIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldBeforeValue, vs...))
}

// BeforeValueNotIn applies the NotIn predicate on the "before_value" field.
func BeforeValueNotIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldBeforeValue, vs...))
}

// BeforeValueGT applies the GT predicate on the "before_value" field.
func BeforeValueGT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldBeforeValue, v))
}

// BeforeValueGTE applies the GTE predicate on the "before_value" field.
func BeforeValueGTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldBeforeValue, v))
}

// BeforeValueLT applies the LT predicate on the "before_value" field.
func BeforeValueLT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldBeforeValue, v))
}

// BeforeValueLTE applies the LTE predicate on the "before_value" field.
func BeforeValueLTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldBeforeValue, v))
}

// BeforeValueContains applies the Contains predicate on the "before_value" field.
func BeforeValueContains(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContains(FieldBeforeValue, v))
}

// BeforeValueHasPrefix applies the HasPrefix predicate on the "before_value" field.
func BeforeValueHasPrefix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasPrefix(FieldBeforeValue, v))
}

// BeforeValueHasSuffix applies the HasSuffix predicate on the "before_value" field.
func BeforeValueHasSuffix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasSuffix(FieldBeforeValue, v))
}

// BeforeValueIsNil applies the IsNil predicate on the "before_value" field.
func BeforeValueIsNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIsNull(FieldBeforeValue))
}

// BeforeValueNotNil applies the NotNil predicate on the "before_value" field.
func BeforeValueNotNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotNull(FieldBeforeValue))
}

// BeforeValueEqualFold applies the EqualFold predicate on the "before_value" field.
func BeforeValueEqualFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEqualFold(FieldBeforeValue, v))
}

// BeforeValueContainsFold applies the ContainsFold predicate on the "before_value" field.
func BeforeValueContainsFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContainsFold(FieldBeforeValue, v))
}

// AfterValueEQ applies the EQ predicate on the "after_value" field.
func AfterValueEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldAfterValue, v))
}

// AfterValueNEQ applies the NEQ predicate on the "after_value" field.
func AfterValueNEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldAfterValue, v))
}

// AfterValueIn applies the In predicate on the "after_value" field.
func AfterValueIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldAfterValue, vs...))
}

// AfterValueNotIn applies the NotIn predicate on the "after_value" field.
func AfterValueNotIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldAfterValue, vs...))
}

// AfterValueGT applies the GT predicate on the "after_value" field.
func AfterValueGT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldAfterValue, v))
}

// AfterValueGTE applies the GTE predicate on the "after_value" field.
func AfterValueGTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldAfterValue, v))
}

// AfterValueLT applies the LT predicate on the "after_value" field.
func AfterValueLT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldAfterValue, v))
}

// AfterValueLTE applies the LTE predicate on the "after_value" field.
func AfterValueLTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldAfterValue, v))
}

// AfterValueContains applies the Contains predicate on the "after_value" field.
func AfterValueContains(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContains(FieldAfterValue, v))
}

// AfterValueHasPrefix applies the HasPrefix predicate on the "after_value" field.
func AfterValueHasPrefix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasPrefix(FieldAfterValue, v))
}

// AfterValueHasSuffix applies the HasSuffix predicate on the "after_value" field.
func AfterValueHasSuffix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasSuffix(FieldAfterValue, v))
}

// AfterValueIsNil applies the IsNil predicate on the "after_value" field.
func AfterValueIsNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIsNull(FieldAfterValue))
}

// AfterValueNotNil applies the NotNil predicate on the "after_value" field.
func AfterValueNotNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotNull(FieldAfterValue))
}

// AfterValueEqualFold applies the EqualFold predicate on the "after_value" field.
func AfterValueEqualFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEqualFold(FieldAfterValue, v))
}

// AfterValueContainsFold applies the ContainsFold predicate on the "after_value" field.
func AfterValueContainsFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContainsFold(FieldAfterValue, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotNull(FieldUserID))
}

// UserEmailEQ applies the EQ predicate on the "user_email" field.
func UserEmailEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldUserEmail, v))
}

// UserEmailNEQ applies the NEQ predicate on the "user_email" field.
func UserEmailNEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldUserEmail, v))
}

// UserEmailIn applies the In predicate on the "user_email" field.
func UserEmailIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldUserEmail, vs...))
}

// UserEmailNotIn applies the NotIn predicate on the "user_email" field.
func UserEmailNotIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldUserEmail, vs...))
}

// UserEmailGT applies the GT predicate on the "user_email" field.
func UserEmailGT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldUserEmail, v))
}

// UserEmailGTE applies the GTE predicate on the "user_email" field.
func UserEmailGTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldUserEmail, v))
}

// UserEmailLT applies the LT predicate on the "user_email" field.
func UserEmailLT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldUserEmail, v))
}

// UserEmailLTE applies the LTE predicate on the "user_email" field.
func UserEmailLTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldUserEmail, v))
}

// UserEmailContains applies the Contains predicate on the "user_email" field.
func UserEmailContains(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContains(FieldUserEmail, v))
}

// UserEmailHasPrefix applies the HasPrefix predicate on the "user_email" field.
func UserEmailHasPrefix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasPrefix(FieldUserEmail, v))
}

// UserEmailHasSuffix applies the HasSuffix predicate on the "user_email" field.
func UserEmailHasSuffix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasSuffix(FieldUserEmail, v))
}

// UserEmailIsNil applies the IsNil predicate on the "user_email" field.
func UserEmailIsNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIsNull(FieldUserEmail))
}

// UserEmailNotNil applies the NotNil predicate on the "user_email" field.
func UserEmailNotNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotNull(FieldUserEmail))
}

// UserEmailEqualFold applies the EqualFold predicate on the "user_email" field.
func UserEmailEqualFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEqualFold(FieldUserEmail, v))
}

// UserEmailContainsFold applies the ContainsFold predicate on the "user_email" field.
func UserEmailContainsFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContainsFold(FieldUserEmail, v))
}

// UserNameEQ applies the EQ predicate on the "user_name" field.
func UserNameEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldUserName, v))
}

// UserNameNEQ applies the NEQ predicate on the "user_name" field.
func UserNameNEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldUserName, v))
}

// UserNameIn applies the In predicate on the "user_name" field.
func UserNameIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldUserName, vs...))
}

// UserNameNotIn applies the NotIn predicate on the "user_name" field.
func UserNameNotIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldUserName, vs...))
}

// UserNameGT applies the GT predicate on the "user_name" field.
func UserNameGT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldUserName, v))
}

// UserNameGTE applies the GTE predicate on the "user_name" field.
func UserNameGTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldUserName, v))
}

// UserNameLT applies the LT predicate on the "user_name" field.
func UserNameLT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldUserName, v))
}

// UserNameLTE applies the LTE predicate on the "user_name" field.
func UserNameLTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldUserName, v))
}

// UserNameContains applies the Contains predicate on the "user_name" field.
func UserNameContains(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContains(FieldUserName, v))
}

// UserNameHasPrefix applies the HasPrefix predicate on the "user_name" field.
func UserNameHasPrefix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasPrefix(FieldUserName, v))
}

// UserNameHasSuffix applies the HasSuffix predicate on the "user_name" field.
func UserNameHasSuffix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasSuffix(FieldUserName, v))
}

// UserNameIsNil applies the IsNil predicate on the "user_name" field.
func UserNameIsNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIsNull(FieldUserName))
}

// UserNameNotNil applies the NotNil predicate on the "user_name" field.
func UserNameNotNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotNull(FieldUserName))
}

// UserNameEqualFold applies the EqualFold predicate on the "user_name" field.
func UserNameEqualFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEqualFold(FieldUserName, v))
}

// UserNameContainsFold applies the ContainsFold predicate on the "user_name" field.
func UserNameContainsFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContainsFold(FieldUserName, v))
}

// OperatorUserIDEQ applies the EQ predicate on the "operator_user_id" field.
func OperatorUserIDEQ(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldOperatorUserID, v))
}

// OperatorUserIDNEQ applies the NEQ predicate on the "operator_user_id" field.
func OperatorUserIDNEQ(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldOperatorUserID, v))
}

// OperatorUserIDIn applies the In predicate on the "operator_user_id" field.
func OperatorUserIDIn(vs ...int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDNotIn applies the NotIn predicate on the "operator_user_id" field.
func OperatorUserIDNotIn(vs ...int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDGT applies the GT predicate on the "operator_user_id" field.
func OperatorUserIDGT(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldOperatorUserID, v))
}

// OperatorUserIDGTE applies the GTE predicate on the "operator_user_id" field.
func OperatorUserIDGTE(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldOperatorUserID, v))
}

// OperatorUserIDLT applies the LT predicate on the "operator_user_id" field.
func OperatorUserIDLT(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldOperatorUserID, v))
}

// OperatorUserIDLTE applies the LTE predicate on the "operator_user_id" field.
func OperatorUserIDLTE(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldOperatorUserID, v))
}

// OperatorUserIDIsNil applies the IsNil predicate on the "operator_user_id" field.
func OperatorUserIDIsNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIsNull(FieldOperatorUserID))
}

// OperatorUserIDNotNil applies the NotNil predicate on the "operator_user_id" field.
func OperatorUserIDNotNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotNull(FieldOperatorUserID))
}

// OperatorEmailEQ applies the EQ predicate on the "operator_email" field.
func OperatorEmailEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldOperatorEmail, v))
}

// OperatorEmailNEQ applies the NEQ predicate on the "operator_email" field.
func OperatorEmailNEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldOperatorEmail, v))
}

// OperatorEmailIn applies the In predicate on the "operator_email" field.
func OperatorEmailIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldOperatorEmail, vs...))
}

// OperatorEmailNotIn applies the NotIn predicate on the "operator_email" field.
func OperatorEmailNotIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldOperatorEmail, vs...))
}

// OperatorEmailGT applies the GT predicate on the "operator_email" field.
func OperatorEmailGT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldOperatorEmail, v))
}

// OperatorEmailGTE applies the GTE predicate on the "operator_email" field.
func OperatorEmailGTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldOperatorEmail, v))
}

// OperatorEmailLT applies the LT predicate on the "operator_email" field.
func OperatorEmailLT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldOperatorEmail, v))
}

// OperatorEmailLTE applies the LTE predicate on the "operator_email" field.
func OperatorEmailLTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldOperatorEmail, v))
}

// OperatorEmailContains applies the Contains predicate on the "operator_email" field.
func OperatorEmailContains(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContains(FieldOperatorEmail, v))
}

// OperatorEmailHasPrefix applies the HasPrefix predicate on the "operator_email" field.
func OperatorEmailHasPrefix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasPrefix(FieldOperatorEmail, v))
}

// OperatorEmailHasSuffix applies the HasSuffix predicate on the "operator_email" field.
func OperatorEmailHasSuffix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasSuffix(FieldOperatorEmail, v))
}

// OperatorEmailIsNil applies the IsNil predicate on the "operator_email" field.
func OperatorEmailIsNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIsNull(FieldOperatorEmail))
}

// OperatorEmailNotNil applies the NotNil predicate on the "operator_email" field.
func OperatorEmailNotNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotNull(FieldOperatorEmail))
}

// OperatorEmailEqualFold applies the EqualFold predicate on the "operator_email" field.
func OperatorEmailEqualFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEqualFold(FieldOperatorEmail, v))
}

// OperatorEmailContainsFold applies the ContainsFold predicate on the "operator_email" field.
func OperatorEmailContainsFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContainsFold(FieldOperatorEmail, v))
}

// OperatorNameEQ applies the EQ predicate on the "operator_name" field.
func OperatorNameEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldOperatorName, v))
}

// OperatorNameNEQ applies the NEQ predicate on the "operator_name" field.
func OperatorNameNEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldOperatorName, v))
}

// OperatorNameIn applies the In predicate on the "operator_name" field.
func OperatorNameIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldOperatorName, vs...))
}

// OperatorNameNotIn applies the NotIn predicate on the "operator_name" field.
func OperatorNameNotIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldOperatorName, vs...))
}

// OperatorNameGT applies the GT predicate on the "operator_name" field.
func OperatorNameGT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldOperatorName, v))
}

// OperatorNameGTE applies the GTE predicate on the "operator_name" field.
func OperatorNameGTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldOperatorName, v))
}

// OperatorNameLT applies the LT predicate on the "operator_name" field.
func OperatorNameLT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldOperatorName, v))
}

// OperatorNameLTE applies the LTE predicate on the "operator_name" field.
func OperatorNameLTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldOperatorName, v))
}

// OperatorNameContains applies the Contains predicate on the "operator_name" field.
func OperatorNameContains(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContains(FieldOperatorName, v))
}

// OperatorNameHasPrefix applies the HasPrefix predicate on the "operator_name" field.
func OperatorNameHasPrefix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasPrefix(FieldOperatorName, v))
}

// OperatorNameHasSuffix applies the HasSuffix predicate on the "operator_name" field.
func OperatorNameHasSuffix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasSuffix(FieldOperatorName, v))
}

// OperatorNameIsNil applies the IsNil predicate on the "operator_name" field.
func OperatorNameIsNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIsNull(FieldOperatorName))
}

// OperatorNameNotNil applies the NotNil predicate on the "operator_name" field.
func OperatorNameNotNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotNull(FieldOperatorName))
}

// OperatorNameEqualFold applies the EqualFold predicate on the "operator_name" field.
func OperatorNameEqualFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEqualFold(FieldOperatorName, v))
}

// OperatorNameContainsFold applies the ContainsFold predicate on the "operator_name" field.
func OperatorNameContainsFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContainsFold(FieldOperatorName, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContainsFold(FieldNotes, v))
}

// ClientIPEQ applies the EQ predicate on the "client_ip" field.
func ClientIPEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldClientIP, v))
}

// ClientIPNEQ applies the NEQ predicate on the "client_ip" field.
func ClientIPNEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldClientIP, v))
}

// ClientIPIn applies the In predicate on the "client_ip" field.
func ClientIPIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldClientIP, vs...))
}

// ClientIPNotIn applies the NotIn predicate on the "client_ip" field.
func ClientIPNotIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldClientIP, vs...))
}

// ClientIPGT applies the GT predicate on the "client_ip" field.
func ClientIPGT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldClientIP, v))
}

// ClientIPGTE applies the GTE predicate on the "client_ip" field.
func ClientIPGTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldClientIP, v))
}

// ClientIPLT applies the LT predicate on the "client_ip" field.
func ClientIPLT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldClientIP, v))
}

// ClientIPLTE applies the LTE predicate on the "client_ip" field.
func ClientIPLTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldClientIP, v))
}

// ClientIPContains applies the Contains predicate on the "client_ip" field.
func ClientIPContains(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContains(FieldClientIP, v))
}

// ClientIPHasPrefix applies the HasPrefix predicate on the "client_ip" field.
func ClientIPHasPrefix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasPrefix(FieldClientIP, v))
}

// ClientIPHasSuffix applies the HasSuffix predicate on the "client_ip" field.
func ClientIPHasSuffix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasSuffix(FieldClientIP, v))
}

// ClientIPIsNil applies the IsNil predicate on the "client_ip" field.
func ClientIPIsNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIsNull(FieldClientIP))
}

// ClientIPNotNil applies the NotNil predicate on the "client_ip" field.
func ClientIPNotNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotNull(FieldClientIP))
}

// ClientIPEqualFold applies the EqualFold predicate on the "client_ip" field.
func ClientIPEqualFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEqualFold(FieldClientIP, v))
}

// ClientIPContainsFold applies the ContainsFold predicate on the "client_ip" field.
func ClientIPContainsFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContainsFold(FieldClientIP, v))
}

// AuthMethodEQ applies the EQ predicate on the "auth_method" field.
func AuthMethodEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldAuthMethod, v))
}

// AuthMethodNEQ applies the NEQ predicate on the "auth_method" field.
func AuthMethodNEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldAuthMethod, v))
}

// AuthMethodIn applies the In predicate on the "auth_method" field.
func AuthMethodIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldAuthMethod, vs...))
}

// AuthMethodNotIn applies the NotIn predicate on the "auth_method" field.
func AuthMethodNotIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldAuthMethod, vs...))
}

// AuthMethodGT applies the GT predicate on the "auth_method" field.
func AuthMethodGT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldAuthMethod, v))
}

// AuthMethodGTE applies the GTE predicate on the "auth_method" field.
func AuthMethodGTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldAuthMethod, v))
}

// AuthMethodLT applies the LT predicate on the "auth_method" field.
func AuthMethodLT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldAuthMethod, v))
}

// AuthMethodLTE applies the LTE predicate on the "auth_method" field.
func AuthMethodLTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldAuthMethod, v))
}

// AuthMethodContains applies the Contains predicate on the "auth_method" field.
func AuthMethodContains(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContains(FieldAuthMethod, v))
}

// AuthMethodHasPrefix applies the HasPrefix predicate on the "auth_method" field.
func AuthMethodHasPrefix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasPrefix(FieldAuthMethod, v))
}

// AuthMethodHasSuffix applies the HasSuffix predicate on the "auth_method" field.
func AuthMethodHasSuffix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasSuffix(FieldAuthMethod, v))
}

// AuthMethodIsNil applies the IsNil predicate on the "auth_method" field.
func AuthMethodIsNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIsNull(FieldAuthMethod))
}

// AuthMethodNotNil applies the NotNil predicate on the "auth_method" field.
func AuthMethodNotNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotNull(FieldAuthMethod))
}

// AuthMethodEqualFold applies the EqualFold predicate on the "auth_method" field.
func AuthMethodEqualFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEqualFold(FieldAuthMethod, v))
}

// AuthMethodContainsFold applies the ContainsFold predicate on the "auth_method" field.
func AuthMethodContainsFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContainsFold(FieldAuthMethod, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContainsFold(FieldRequestID, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldContainsFold(FieldSource, v))
}

// LegacyRedeemCodeIDEQ applies the EQ predicate on the "legacy_redeem_code_id" field.
func LegacyRedeemCodeIDEQ(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldLegacyRedeemCodeID, v))
}

// LegacyRedeemCodeIDNEQ applies the NEQ predicate on the "legacy_redeem_code_id" field.
func LegacyRedeemCodeIDNEQ(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldLegacyRedeemCodeID, v))
}

// LegacyRedeemCodeIDIn applies the In predicate on the "legacy_redeem_code_id" field.
func LegacyRedeemCodeIDIn(vs ...int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldLegacyRedeemCodeID, vs...))
}

// LegacyRedeemCodeIDNotIn applies the NotIn predicate on the "legacy_redeem_code_id" field.
func LegacyRedeemCodeIDNotIn(vs ...int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldLegacyRedeemCodeID, vs...))
}

// LegacyRedeemCodeIDGT applies the GT predicate on the "legacy_redeem_code_id" field.
func LegacyRedeemCodeIDGT(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldLegacyRedeemCodeID, v))
}

// LegacyRedeemCodeIDGTE applies the GTE predicate on the "legacy_redeem_code_id" field.
func LegacyRedeemCodeIDGTE(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldLegacyRedeemCodeID, v))
}

// LegacyRedeemCodeIDLT applies the LT predicate on the "legacy_redeem_code_id" field.
func LegacyRedeemCodeIDLT(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldLegacyRedeemCodeID, v))
}

// LegacyRedeemCodeIDLTE applies the LTE predicate on the "legacy_redeem_code_id" field.
func LegacyRedeemCodeIDLTE(v int64) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldLegacyRedeemCodeID, v))
}

// LegacyRedeemCodeIDIsNil applies the IsNil predicate on the "legacy_redeem_code_id" field.
func LegacyRedeemCodeIDIsNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIsNull(FieldLegacyRedeemCodeID))
}

// LegacyRedeemCodeIDNotNil applies the NotNil predicate on the "legacy_redeem_code_id" field.
func LegacyRedeemCodeIDNotNil() predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotNull(FieldLegacyRedeemCodeID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdminUserAdjustment) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdminUserAdjustment) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdminUserAdjustment) predicate.AdminUserAdjustment {
	return predicate.AdminUserAdjustment(sql.NotPredicates(p))
}
